### ISSUE TITLE
Adapting Text is needed

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#153]
Scott Hollier (http://hollier.info/wcag21draft/):
The Adapting Text SC would be a fantastic addition.  As a high contrast color user its often the case that websites don’t account for user-defined colors and you end up in situations where text gets garbled or you can end up with for example, black text on a  black background.  The specifics of this need some work but I’m a big fan of the principle.

**Comment by lauracarlson** [comment]
Hi Scott,

You wrote,

> The Adapting Text SC would be a fantastic addition. As a high contrast color user its often the case that websites don’t account for user-defined colors and you end up in situations where text gets garbled or you can end up with for example, black text on a black background. The specifics of this need some work but I’m a big fan of the principle.

Thank you for your comment and support of the Adapting Text SC. The Working Group seeks to include overriding text color and background color as part of this SC, but is not yet able to identify a way to do so that is sufficiently testable. If you have suggestions, we would love to hear them.

The latest SC text, which the AG Working Group has agreed to accept into editors draft for public comment is:

If the technologies being used allow the [user agent](https://www.w3.org/TR/WCAG20/#useragentdef) to [adapt](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/adapt.html) [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) of [text](https://www.w3.org/TR/WCAG20/#textdef), then no loss of [essential](https://www.w3.org/TR/WCAG20/#essentialdef) content or functionality occurs by adapting all of the following:

1. line height (line spacing) to at least 1.5 times the font size
2. spacing underneath paragraphs to at least 2 times the font size
3. letter spacing (tracking) to at least 0.12 times the font size
4. word spacing to at least 0.16 times the font size

Note: Examples of text that are typically not affected by [style properties](https://rawgit.com/w3c/wcag21/adapting-text_ISSUE-74-78-79/guidelines/terms/21/style-properties.html) are open [captions](https://www.w3.org/TR/WCAG20/#captionsdef) and [images of text](https://www.w3.org/TR/WCAG20/#images-of-textdef), which are not expected to adapt.

Editor's note: The Working Group seeks to include overriding text color, background color, and font-family as part of this SC, but is not yet able to identify a way to do so that is sufficiently testable.

Thanks again,
Laura

**Comment by lauracarlson** [comment]
- Proposed solution to  add color bullets to the SC is in #348.
- [Discussion on the AG list](https://github.com/w3c/wcag21/issues/348).

**Comment by lauracarlson** [comment]
[Draft response for Issue 153 Adapting Text)](https://lists.w3.org/Archives/Public/w3c-wai-gl/2017JulSep/1016.html) - 14 September 2017

**Comment by awkawk** [comment]
Response to Scott:
Thank you for your comment.

We agree that the adapting text SC is a good addition. However, the
color requirement has been removed as the Low Vision Task Force has
found that users can override author CSS color rules. Users need to
carefully craft their user rules to be at the same or higher
specificity level as an author's rules. This may necessitate users
investigating an author's markup.

Beyond this WCAG has 2 related failure techniques in place for authors to heed:

F3: Failure of Success Criterion 1.1.1 due to using CSS to include
images that convey important information [1]

F24: Failure of Success Criterion 1.4.3, 1.4.6 and 1.4.8 due to
specifying foreground colors without specifying background colors or
vice versa [2].
