### ISSUE TITLE
1.4.10 Linearization - Testing methods not clear enough

### ISSUE THREAD

**Issue by FionaHolder** [w3c/wcag21#160]
http://myaccessible.website/2017/03/wcag-2-1-review-1-4-10-linearization/

This success criterion is not clear enough on who provides the mechanism for reflowing content to a single column, and what that mechanism should be, though from the comments it appears that the reflow will be provided by user agents/scripts and not implemented by the developers.

The main issue is that the recommended method for testing is to switch off CSS, but this will cause content that has been hidden using display:none or similar to become visible. With responsive sites, the reliance on CSS to show / hide content has increased and so switching it off could cause very confusing displays indeed.

I feel that to make this a solid SC, there needs to be some form of browser plugin or script that is endorsed by the W3C for testing the reflow in HTML. Otherwise, there is too much subjectivity in the testing technique, and just switching off CSS completely will be too problematic. ​

**Comment by alastc** [comment]
Hi Fiona,

That is in progress, you can see an early example (and select the 'linearise' link under 'secondary content area').

That is intended to be an open source bookmarklet, and might turn into a extension, but the main aim is to test the SC. (NB: It doesn't unhide elements, and maintains the flexbox order if there is one.)

I don't think the W3C would endorse a particular extension, but what it will enable is the establishment of techniques and failures that support the SC. The SC has to be about attributes of the content, rather than a particular user-agent implementation.

**Comment by steverep** [comment]
Recommend this issue be closed as the Linearization SC did not reach working group consensus and thus will not be in 2.1.  Much of the desired content requirements, however, are covered by the Zoom Content SC.

**Comment by awkawk** [comment]
@FionaHolder  As Steve indicated above, there is a new SC named "Zoom Content" that is related but different from the original Linearization SC. We would appreciate your thoughts on this new SC: https://www.w3.org/TR/WCAG21/#zoom-content
