### ISSUE TITLE
Microsoft comment on Resize Content

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#180]
Clarity of text: 

a. It is unclear as to whether the 400% increase is measured by area or dimension.  A 2x increase in height and width would increase an object area by 4x.  While a 4x increase in height and width would increase an object area by 16x.

b. Better explanation and examples of what content necessitates fixed spatial layout is needed.  How does something like a PowerPoint deck meet this or is it consider part of the exception?  What about a PDF document?

Helpfulness:

a. The proposal text seems to penalize content that are made to be big by default in order to assist low-vision users.  As an alternative, the working group should consider minimum vertical or horizonal dimension where the content can zoom to without two-dimensional scrolling.

b. Note that in many cases the user who needs to zoom the content may also zoom the onscreen keyboard.  This will not only cut down functional screen real estate, but it also forces horizonal scrolling in the keyboard part of the screen while the content generally scrolling vertically.

c. Abstracting this success criterion to the OS level, since the same user who wants to zoom 4x on the content will want to do the same for everything else and that EN 301549 will try to abstract this SC to apply to mobile apps.  What does this imply about the magnifier feature from the OS?  Is it trying to say that two-dimensional scrolling is ok (and magnifier features are appropriate) once the need goes beyond 4x?

**Comment by mraccess77** [comment]
@alexswli  wrote b. Note that in many cases the user who needs to zoom the content may also zoom the onscreen keyboard. This will not only cut down functional screen real estate, but it also forces horizonal scrolling in the keyboard part of the screen while the content generally scrolling vertically.

Personally I find it difficult when only the content area and not the on-screen keyboard zoom on a phone because the area is so small its hard for me to control.  I'd prefer the whole screen and keyboard zoom.  Although I likely will type in the unzoomed state and zoom in to read the content and then zoom back out again.  The being is that each person with low vision may have different needs.  Ideally I wouldn't need to use native magnification because the content would enlarge.  An example of this is Skype for Business.  I use large text on iOS but the Skype for Business app does not honor the large text setting even though the app is a single column linear layout with vertical scrolling for messages and could accommodate large text.  My on-screen keyboard is large and high contrast.  But I have to zoom in with the iOS magnifier feature to read the text messages from my co-workers.  This is very frustrating.

@alexswli  wrote c. Abstracting this success criterion to the OS level, since the same user who wants to zoom 4x on the content will want to do the same for everything else and that EN 301549 will try to abstract this SC to apply to mobile apps. What does this imply about the magnifier feature from the OS? Is it trying to say that two-dimensional scrolling is ok (and magnifier features are appropriate) once the need goes beyond 4x?

For the mobile UI I use the large text feature.  But at some point that can only go so large.  For me it is good but for others there comes a point where they would need to use magnification for the UI.  So on my iPhone I generally don't use the magnification feature to see the screen but instead us the large text feature in iOS because I don't like scrolling and I can see the whole screen at once.  Using magnification where I must pan is a last resort as it makes me dizzy.

**Comment by alastc** [comment]
(Replying as myself for clarifications, not on behalf of the working group.)

> a. It is unclear as to whether the 400% increase is measured by area or dimension. A 2x increase in height and width would increase an object area by 4x. While a 4x increase in height and width would increase an object area by 16x.

This is the only comment making this point, given that all desktop browsers have a built-in zoom based on a percentage increase, I think it is clear enough for the SC text. However, we can clarify that in the understanding.

> b. Better explanation and examples of what content necessitates fixed spatial layout is needed. How does something like a PowerPoint deck meet this or is it consider part of the exception? What about a PDF document?

We can update the description, I assume you weren't asking for examples in the SC text? 
PDF documents can be zoomed and reflowed (when tagged etc). Powerpoint decks are not 'web content', but I assume you mean the web equivalents? Is possible in that context to reflow the content / interface?

> a. The proposal text seems to penalize content that are made to be big by default in order to assist low-vision users. As an alternative, the working group should consider minimum vertical or horizonal dimension where the content can zoom to without two-dimensional scrolling.

If content is made big for people with low vision, is this not an alternative version of some default content? The same argument applies to the original 1.4.4, but a proportional increase is the only real option for web content, and I think it generally works because the vast majority of interfaces are created for a 'default' audience that does not have low vision.

Is there an example of this you could point to? 

> b. Note that in many cases the user who needs to zoom the content may also zoom the onscreen keyboard. 

I haven't come across an onscreen keyboard that is "web content", isn't that something that applies at the OS level?

> c. Abstracting this success criterion to the OS level, since the same user who wants to zoom 4x on the content will want to do the same for everything else and that EN 301549 will try to abstract this SC to apply to mobile apps. What does this imply about the magnifier feature from the OS? Is it trying to say that two-dimensional scrolling is ok (and magnifier features are appropriate) once the need goes beyond 4x?

I think that is less about content-size, and more about device size. Small screen mobile devices generally don't reflow much (if at all), but that doesn't mean the web-content cannot. The scope of WCAG SCs is web-content, where another organisation tries to apply them to mobile apps there needs to be some translation.

**Comment by alastc** [comment]
I think with the [latest version](https://github.com/w3c/wcag21/blob/feec65422c2e205ea27603cb4cbaf8c1025d63ad/guidelines/sc/21/resize-content.html) we've addressed the points above:

* Going with the "320 CSS pixels" equivalent width and including the zoom aspect in a note clarifies the 400% aspect.
* Fixed spacial layout is not used now, and there are examples in a note for the new term.
* Talking to the Low Vision task force, no-one had come across sites that use large text by default. Some have text-sizing widgets, which should not conflict with this SC.
* I don't think on-screen keyboards are generally (ever?) 'web content', and zooming on web content should not affect a native onscreen keyboard.
* This SC doesn't imply anything about native zoom on mobiles, and avoids the question by essentially saying it should work at a small-mobile size.

Please let me know if you have new or other concerns.

**Comment by awkawk** [comment]
@alexswli The concerns you have noted have been addressed in the latest draft of the SC, now called "zoom content": https://www.w3.org/TR/WCAG21/#zoom-content
