### ISSUE TITLE
Microsoft comments on Popup Interference

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#187]
Clarity of Text:

a. This appears to be about pointer covering up tooltip issue.  This appears to be something that browsers should improve.  Asking for content authors to turn off tooltips seems to run counter to helping users with disabilities.

Implementable:

a. As mentioned, this is not a content issue to be addressed by content authors.  Demanding content authors to get around this problem seems to misplace the burden.

**Comment by WayneEDick** [comment]
The tooltip material while critical for usage is beyond WCAG 2.1 scope. I
will be changing that language shortly.  This was a last minute addition
and the support materials do not match the SC language.

Sorry, Wayne Dick

On Thursday, March 30, 2017, alexswli <notifications@github.com> wrote:
> Clarity of Text:
>
> a. This appears to be about pointer covering up tooltip issue. This
appears to be something that browsers should improve. Asking for content
authors to turn off tooltips seems to run counter to helping users with
disabilities.
>
> Implementable:
>
> a. As mentioned, this is not a content issue to be addressed by content
authors. Demanding content authors to get around this problem seems to
misplace the burden.

**Comment by steverep** [comment]
@alexswli, the latest language for this criterion, [Content on Hover or Focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus), is substantially different from that used to generate this comment.  The SC does not require turning off tooltips anymore, and makes an exception for content completely controlled by user agents.  I think it would be safe to close this issue.

**Comment by alexswli** [comment]
I agree
