### ISSUE TITLE
Microsoft comment on Orientation

### ISSUE THREAD

**Issue by alexswli** [w3c/wcag21#193]
Helpfulness: 

a. Some devices may have a preferential orientation. iPhone home screen only works in portrait mode, for example.  Does the iPhone home page fail, if we treat it as a web page.  Or can you say it is essential because there are design features that won't work well in landscape.  Should a page fail if it follows the preferential orientation of the device?  Perhaps we can make that an option.  Based on the benefit and description of the SC, it seems like following the preferential orientation of the device, instead of requiring flexibility of orientation, is the main objective.  If so, this SC actually does not match the problem it is trying to solve.

Implementable:

a. This SC may come into conflict with the Resizing SC which almost forces the use of landscape mode in many cases.

**Comment by patrickhlauke** [comment]
> Should a page fail if it follows the preferential orientation of the device?

as there is, to my knowledge, no way for a page to determine what the environment's preferential orientation is (via CSS, or JS, or otherwise), it seems that this would be a moot point. Unless the suggestion is that the author did a UA sniff or similar to try and ascertain what exact device/environment the page is running in?

Otherwise, the best way to achieve this (making sure the page works in the device/environment's preferential orientation) would be to make sure it works in both portrait and landscape, so it adapts to whatever the preferential orientation is?

**Comment by awkawk** [comment]
I'm sure that a device manufacturer (apple, in your example) might make a claim that the layout of the UI is essential and therefore locking it is necessary. I think that the iPhone home screen would likely be regarded as a failure since there are many other screens on the iPhone (messages, mail) that do rotate - why is the form factor essential for the home area, weather, clock apps but not for these?

I can see an argument for the preferential orientation for a watch much more.

**Comment by alexswli** [comment]
I guess the key question is whether we should factor the device or OS preference. If there is no built-in preference, then it is straight forward and that display orientation should be as flexible as the device and OS allow. On the other end of the spectrum are devices and OS that do not let users rotate, nobody would hold content authors accountable to those situations. But there is this grey area in the middle where it is possible to rotate and yet there is a varying degree (stronger in the case of watches; weaker in the case the an iPhone; somewhere in the middle for some laptops) of preference or convention for one orientation. It strikes me as reasonable to follow the built-in preference.

My general advice in this situation for our Ux folks is that don’t lock an orientation unless it is essential; but if you must lock it, then lock it to the OS/device preference unless it is essential. It is more like a small decision tree than a simple pass/fail approach, but I think it is reasonable for the situation.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by awkawk** [comment]
We believe that the current language addresses your concern:

“Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.”
