### ISSUE TITLE
Learning Disabilities of America - Technology Committee Comments:  WCAG 2.1 For Learning Disabilities and Cognitive Disabilities

### ISSUE THREAD

**Issue by CarolynPhillips143** [w3c/wcag21#211]
Learning Disabilities of America - Technology Committee Comments: 
WCAG 2.1 For Learning Disabilities and Cognitive Disabilities

Thank you for providing this opportunity to comment. It is clear a  significant amount of time, thought and energy has been invested in this document, the SCs and the process. It is refreshing to see a focus being placed on the accessibility needs of people with learning and cognitive impairments. The LDA – Technology Committee applauds these efforts. This Feedback is specifically from Steve Noble, Carolyn Phillips, Maria Kelley, Martha Rust, Liz Persaud and Sam Peters who are members of the LDA – Technology Committee.

Our primary focus was on addressing these questions:

1.	How important are the proposed COGA Success Criteria for users? 
2.	Do the COGA Success Criteria fully address current user needs for digital learning and web content?  

1.	All of the new 10 proposed COGA Success Criteria are important elements for people with learning disabilities and should be kept. The extensive descriptions which are provided in the GitHub comments are excellent. 

We strongly encourage you to keep all of the 10 proposed SC. We appreciate the Plain English Summary. Prioritizing the SC difficult without some type of rubric to score them. We did consider each of these and placed them in 2 Priority groups:
(1) First priority:
•	Support Personalization (Success Criterion 1.3.4)
•	Timeouts (Success Criterion 2.2.6)
•	Familiar Design (minimum) (Success Criterion 3.2.7)
•	Extra Symbols (Success Criterion 3.1.9)
•	Minimize User Errors (Success Criterion 3.3.7)
•	Provide Support (Success Criterion 3.3.9)
•	Undo (Success Criterion 3.3.8)
•	Plain Language (Success Criterion 3.1.7)

(2) Second priority:
•	Manageable Blocks (Success Criterion 3.1.8)
•	Interruptions (minimum) (Success Criterion 2.2.8) 

With that stated, our preference would be for all of these to be adopted. Each one of them has a possible connection to the access needs of people with learning disabilities.

2.	The proposed COGA Success Criteria do address user needs for digital learning and web content. These SC are needed, useful and valued. At the risk of repeating the excellent comments already put together in the GitHub documentation, here are a more thoughts on the SC.

•	Support Personalization (Success Criterion 1.3.4)
o	Value: The ability to control aspects of a user interface such that the user can reduce the complexity of the layout, reduce the number of options and menu items only to those the user wants to see, apply consistent icon usage to those that the user already identifies. 

•	Timeouts (Success Criterion 2.2.6)
o	Value: This is a significant point of frustration for many of us who are users with disabilities. 

•	Interruptions (minimum) (Success Criterion 2.2.8) 
o	Value: This is also a point of frustration for many of us who are users with disabilities. Being able to postpone and suppress these will be a benefit for people with learning disabilities and attention deficit disorders.

•	Plain Language (Success Criterion 3.1.7)
o	Value: People with learning disabilities, especially reading related issues such as dyslexia, find complex technical language more difficult to understand.

•	Manageable Blocks (Success Criterion 3.1.8)
o	Value: From what we have learned in the education setting, this practice has been shown to have an important learning benefit for people with learning disabilities and attention deficit disorders.

•	Extra Symbols (Success Criterion 3.1.9)
o	Value: The use of symbols in addition to text which conveys critical information may be very useful to the population of people who have reading related learning disabilities.

•	Familiar Design (minimum) (Success Criterion 3.2.7)
o	Value: From what we have learned through research, this practice will ease use for people with learning disabilities and attention deficit disorders.

•	Minimize User Errors (Success Criterion 3.3.7)
o	Value: Error notifications may be confusing for people with learning disabilities, so implementing technology which automatically corrects common formatting errors will be very useful. 

•	Undo (Success Criterion 3.3.8)
o	Value: This capability is very important for individuals with LD or AD/HD, as a user may be confused or in a hurry and click on the wrong icon, or may misunderstand what is supposed to occur when a command is issued.

•	Provide Support (Success Criterion 3.3.9)
o	Value: This is a significant issue and resolving this will be a benefit for people with learning disabilities and attention deficit disorders.

Please, contact, Carolyn Phillips, Chair, LDA Technology Committee - carolyn.phillips@gatech.edu for additional information.

**Comment by johnfoliot** [comment]
Proposed Response:
*****
On behalf of the Accessibility Guidelines Working Group:

Thank-you for your thoughtful comments and observations, which this Working Group has reviewed. Some comments inline:

> All of the new 10 proposed COGA Success Criteria are important elements for people with learning disabilities and should be kept. The extensive descriptions which are provided in the GitHub comments are excellent. We strongly encourage you to keep all of the 10 proposed SC. We appreciate the Plain English Summary. 

Thank you. Currently, some of the proposed new Success Criteria (SC) you have commented on appear to be on track for final inclusion to the WCAG 2.1 publication, however there have been some changes to our current Draft that you may not be aware of, and some of the SC you mention have been deferred at this time. 

Rest assured however that even though the SC that are not being included in the current draft have not yet advanced forward in the process, these proposed SC have simply been deferred to a later date (potentially a WCAG 2.2, or something similar going forward), and the Working Group recognizes the importance of the issues driving these proposals. Deferral is not rejection, and many of these proposed SC simply did not meet the maturity level required to advance forward at this time.

Additionally, it is during the Public Comment phase that external observers also have the opportunity to review our work, so that the Working Group can solicit and address comments and concerns from the wider community. Based upon that activity, there *may* be some further adjustments or exclusions, but I am happy to report that at this time it does not appear that this review period has surfaced any significant "show-stoppers".


> We did consider each of these and placed them in 2 Priority groups:
(1) First priority:
•	Support Personalization (Success Criterion 1.3.4)
•	Timeouts (Success Criterion 2.2.6)
•	Familiar Design (minimum) (Success Criterion 3.2.7)
•	Extra Symbols (Success Criterion 3.1.9)
•	Minimize User Errors (Success Criterion 3.3.7)
•	Provide Support (Success Criterion 3.3.9)
•	Undo (Success Criterion 3.3.8)
•	Plain Language (Success Criterion 3.1.7)
>
> (2) Second priority:
•	Manageable Blocks (Success Criterion 3.1.8)
•	Interruptions (minimum) (Success Criterion 2.2.8)


As you may be aware, WCAG 2.0 currently uses three levels of conformance (A, AA, AAA) which are defined at https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-levels-head. Currently, most legislation around the planet uses WCAG as their compliance standard, and require (mandate) conformance to Success Criteria at the A and AA levels, while encouraging conformance to AAA Success Criteria when appropriate. 

I have added the current propsed conformance level(s) to your list below (while also noting relevant changes to the current Draft Spec, found at https://www.w3.org/TR/WCAG21). 

(1) First priority:

- Support Personalization (Success Criterion 1.3.4)
         (IMPORTANT NOTE: This SC has changed, and has now been divided into 2 individual SC: 
  - Success  Criterion 1.3.4 Purpose of Controls (AA) https://www.w3.org/TR/WCAG21/#purpose-of-controls, and 
  - Success Criterion 1.3.5 Contextual Information (AAA) https://www.w3.org/TR/WCAG21/#contextual-information)

- Timeouts (Success Criterion 2.2.6)
         (IMPORTANT NOTE: This SC has changed number, and is now Success Criterion 2.2.8 Timeouts (AAA) https://www.w3.org/TR/WCAG21/#timeouts)

- Familiar Design (minimum) (Success Criterion 3.2.7)
         (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/49#event-1220049239)

- Extra Symbols (Success Criterion 3.1.9)
         (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/50#event-1220049242)

- Minimize User Errors (Success Criterion 3.3.7)
         (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/13#issuecomment-320255298)

- Provide Support (Success Criterion 3.3.9)
         (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/32#event-1220046034, https://github.com/w3c/wcag21/issues/274#issuecomment-329832605)

- Undo (Success Criterion 3.3.8)
         (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/38#event-1220075443)

- Plain Language (Success Criterion 3.1.7)
         (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/42#event-1220047658)

 (2) Second priority:
- Manageable Blocks (Success Criterion 3.1.8)
         (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://github.com/w3c/wcag21/issues/24#event-1220046007)

- Interruptions (minimum) (Success Criterion 2.2.8)
         (Response: this is a proposed SC at AAA https://www.w3.org/TR/WCAG21/#timeouts)


> At the risk of repeating the excellent comments already put together in the GitHub documentation, here are a more thoughts on the SC.

Thank you for the additional feedback. I will ensure that these comments (benefits and value propositions) are documented with the relevant (deferred) SC.

JF (for the Accessibility Guidelines Working Group)

**Comment by joshueoconnor** [comment]
Survey https://www.w3.org/2002/09/wbs/35422/Oct_17th_agwg/results

**Comment by joshueoconnor** [comment]
@lseeman Have you developed a different response based on your comments in the above survey? Or are you happy for this to be closed? Thanks

**Comment by awkawk** [comment]
(Official WG Response)
Thank-you for your thoughtful comments and observations, which this Working Group has reviewed. Some comments inline:

> All of the new 10 proposed COGA Success Criteria are important elements for people with learning disabilities and should be kept. The extensive descriptions which are provided in the GitHub comments are excellent. We strongly encourage you to keep all of the 10 proposed SC. We appreciate the Plain English Summary."

Thank you. Currently, some of the proposed new Success Criteria (SC) you have commented on appear to be on track for final inclusion to the WCAG 2.1 publication, however there have been some changes to our Drafts that you may not be aware of, and some of the SC you mention have been deferred at this time.

Even though the SC that are not being included in the current draft have not yet advanced forward in the process, these proposed SC are being marked as "defer" to ensure review at the next opportunity (potentially a WCAG 2.2, or something similar going forward), and the Working Group recognizes the importance of the issues driving these proposals. Deferral is not rejection, and many of these proposed SC simply did not meet the maturity level required to advance forward at this time.

Additionally, it is during the Public Comment phase that external observers also have the opportunity to review our work, so that the Working Group can solicit and address comments and concerns from the wider community.

> We did consider each of these and placed them in 2 Priority groups: (1) First priority: •	Support Personalization (Success Criterion 1.3.4) •	Timeouts (Success Criterion 2.2.6) •	Familiar Design (minimum) (Success Criterion 3.2.7) •	Extra Symbols (Success Criterion 3.1.9) •	Minimize User Errors (Success Criterion 3.3.7) •	Provide Support (Success Criterion 3.3.9) •	Undo (Success Criterion 3.3.8) •	Plain Language (Success Criterion 3.1.7)

> (2) Second priority: •	Manageable Blocks (Success Criterion 3.1.8) •	Interruptions (minimum) (Success Criterion 2.2.8) </quote>

As you may be aware, WCAG 2.0 currently uses three levels of conformance (A, AA, AAA) which are defined at https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-levels-head. Currently, most legislation around the planet uses WCAG as their compliance standard, and require (mandate) conformance to Success Criteria at the A and AA levels, while encouraging conformance to AAA Success Criteria when appropriate.

We have added the current proposed conformance level(s) to your list below (while also noting relevant changes to the current Draft Spec, found at https://www.w3.org/TR/WCAG21).

(1) First priority:

Support Personalization (Success Criterion 1.3.4) (IMPORTANT NOTE: This SC has changed, and has now been divided into 2 individual SC:

Success Criterion 1.3.4 Purpose of Controls (AA) https://www.w3.org/TR/WCAG21/#purpose-of-controls, and Success Criterion 1.3.5 Contextual Information (AAA) https://www.w3.org/TR/WCAG21/#contextual-information) Timeouts (Success Criterion 2.2.6) (IMPORTANT NOTE: This SC has changed number, and is now Success Criterion 2.2.8 Timeouts (AAA) https://www.w3.org/TR/WCAG21/#timeouts)

Familiar Design (minimum) (Success Criterion 3.2.7) (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #49 (comment))

Extra Symbols (Success Criterion 3.1.9) (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #50 (comment))

Minimize User Errors (Success Criterion 3.3.7) (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #13 (comment))

Provide Support (Success Criterion 3.3.9) (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #32 (comment), #274 (comment))

Undo (Success Criterion 3.3.8) (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #38 (comment))

Plain Language (Success Criterion 3.1.7) (Response: Was proposed at Level (A), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #42 (comment))

(2) Second priority:

Manageable Blocks (Success Criterion 3.1.8) (Response: Was proposed at Level (AA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. #24 (comment))

Interruptions (minimum) (Success Criterion 2.2.8) (Response:Was proposed at Level (AAA), however the Working Group has not reached consensus on this proposed SC so it is deferred for future consideration. https://www.w3.org/TR/WCAG21/#timeouts)

While many Success Criteria have not reached consensus, at present there are still several Success Criteria proposed that will offer benefit to users with cognitive disabilities. These include: 1.3.4 Identify Common Purpose (AA) 1.3.5 Contextual Information (AAA) 1.4.10 Reflow (AA) 1.4.12 Text Spacing (AA) 2.2.6 Timeouts (AAA) 2.4.12 Label in Name (A) 2.5.3 Target Size (AA) 2.5.4 Target Size (Enhanced) (AAA) 3.2.6 Status Changes (AA)
