### ISSUE TITLE
Oracle comment on 1.4.10 Linearization

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#213]
We don't think the title of this SC of linearization is a good title. Linearization is already associated with Meaningful Sequence Calling this linearization will confuse developers about its purpose.

There are many places where linearizing all the content of the page would not be helpful. Take for example an IDE which has multiple panels and a main document window. If I were to linearize this document all of the panels would be either at the beginning or the end of the document. If I need to use these panels to modify the content then I would need to scroll all the way to the top or the bottom of the content in order to do so. We should target this SC on linearizing blocks of content, or potentially linearizing the components of the page, without requiring the entire page to be linearized.

**Comment by WayneEDick** [comment]
The Integrated Development Environment is a good example of why linearization is necessary. 
The task pane model does not work for large print because it forces enlargement without word wrapping.  This is why a linear representation is needed. If the author follows information and relationships (1.3.1) and role, state, value (4.1.2) the task panes regions will be identified by headings or landmarks that users can apply to jump from task pane to task pane.

When possible I linearize every page I use and navigate with headings using NVDA.

**Comment by steverep** [comment]
Recommend this issue be closed as the Linearization SC did not reach working group consensus and thus will not be in 2.1.  Much of the desired content requirements, however, are covered by the Zoom Content SC.

**Comment by awkawk** [comment]
@cwadamsoforacle With the changes in https://www.w3.org/TR/WCAG21/#zoom-content your comment on requiring linearization of web pages is no longer applicable to the current version so closing this issue.
