### ISSUE TITLE
Oracle comment on 2.6.2 Orientation

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/wcag21#235]
It is not clear from the text whether orientation changes need to be supported or whether an application can remain in the same orientation once it has started regardless of whether or not the device is subsequently rotated.

**Comment by marcjohlic** [comment]
@cwadamsoforacle the basic intent was that the content is not locked in any orientation - at any time.  Therefore orientation changes need to be supported when the device is rotated (unless a specific orientation is essential for use).  

We'll discuss this in the Task Force to see if there is better wording to convey this.

**Comment by jnurthen** [comment]
@marcjohlic The only use case mentioned in #70 is "Users with dexterity impairments, who have a mounted mobile device will be able to use the content in their fixed orientation". If the device is mounted why would an application need to support changing orientation once it has started?

**Comment by DavidMacDonald** [comment]
Suggest an amendment
https://github.com/w3c/wcag21/issues/70#issuecomment-299317384

**Comment by awkawk** [comment]
Question from the call on this point - is it harder for an application to define the appropriate layout at any arbitrary time in the use of the application than it is at the start?

**Comment by jnurthen** [comment]
You have to re-run all of the layout code. I know of at least one tech stack we have that only does this at page load or browser re-size. It does not do it at a zoom event. I do not know if it does it at re-orientation (it may but I have no knowledge whether it does or not)

What is the accessibility reason that we need to support re-orientation? I know it is nice but I don't see an accessibility based reason cited.

**Comment by marcjohlic** [comment]
@jnurthen the use case that comes to mind for me is more of a Low Vis situation:  There are times where I'm viewing a site on my phone (portrait) - the text is too small - and if I zoom in I'm forced to scroll horizontally to view all of the content at a decent text size. 
 If I rotate my phone to landscape, that gives me a wider viewport and larger font, reducing or eliminating the need to scroll horizontally. 

Just to note though, this SC is only dealing with authors NOT locking the display orientation (portrait or landscape) - and not zoom levels.  (Users can still lock their preference at the hardware, OS, or app level [if provided]).  We just don't want authors forcing an orientation on users (unless essential).

The tech stack you're referring to - if it re-runs, the layout code at browser resize, wouldn't that happen rotating from portrait to landscape (or vice versa) - because the browser width would resize.

**Comment by joshueoconnor** [comment]
@cwadamsoforacle This looks like it is overtaken by event - and regarding your original comment - the SC in the FPWD is available at https://www.w3.org/TR/WCAG21/#orientation
