### ISSUE TITLE
WebAIM Feedback - SC 1.4.16 – Popup Interference

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#255]
It’s difficult to comment on this success criterion because the [descriptions and scenarios presented for it](https://github.com/w3c/wcag21/issues/75) do not at all match the success criterion text. It is entirely unclear what the intention of this SC even is, but I’ll attempt to address some of the issues as we understand them.

The SC language clearly exempts user agent rendering of title text, yet the descriptions and examples refer specifically and almost exclusively to user agent rendering of title text. Because title text rendering is primarily controlled by the user agent, we believe title attribute presentation should not be covered by this SC.

The descriptions refer to enlarged mouse cursors obscuring ‘tooltip’ content and describe allowing multiple mechanisms for triggering the ‘tooltip’ content (this is already partially covered by keyboard guidelines), but the SC text addresses neither of these. There’s clearly an editorial disconnect here.

Presuming that the SC is actually regarding ‘tooltip’ content obscuring triggering content (e.g., a tooltip for a link obscures the link text), this is primarily handled by the user agent or does not seem to be a disability-specific issue, but a general usability and design consideration that does not have place in accessibility guidelines. If nobody can see the triggering content, then there is no disparate experience for users with disabilities. It also is unreasonable to require that authors provide a mechanism to turn off tooltip content when this interaction model may be necessary and is otherwise conformant.

WebAIM does not support the adoption of this SC as drafted.

**Comment by WayneEDick** [comment]
Jared,
This was a last minute item. At first we looked at tooltips that block the
ability to activate content. Then we realized that many author generated
notifications both informational and including controls cover other
important information.  The idea is to provide a way to hide and be able to
recall the information as needed.

We may not get this one done this time.

Wayne

On Friday, March 31, 2017, jared-w-smith <notifications@github.com> wrote:
> It’s difficult to comment on this success criterion because the
descriptions and scenarios presented for it do not at all match the success
criterion text. It is entirely unclear what the intention of this SC even
is, but I’ll attempt to address some of the issues as we understand them.
>
> The SC language clearly exempts user agent rendering of title text, yet
the descriptions and examples refer specifically and almost exclusively to
user agent rendering of title text. Because title text rendering is
primarily controlled by the user agent, we believe title attribute
presentation should not be covered by this SC.
>
> The descriptions refer to enlarged mouse cursors obscuring ‘tooltip’
content and describe allowing multiple mechanisms for triggering the
‘tooltip’ content (this is already partially covered by keyboard
guidelines), but the SC text addresses neither of these. There’s clearly an
editorial disconnect here.
>
> Presuming that the SC is actually regarding ‘tooltip’ content obscuring
triggering content (e.g., a tooltip for a link obscures the link text),
this is primarily handled by the user agent or does not seem to be a
disability-specific issue, but a general usability and design consideration
that does not have place in accessibility guidelines. If nobody can see the
triggering content, then there is no disparate experience for users with
disabilities. It also is unreasonable to require that authors provide a
mechanism to turn off tooltip content when this interaction model may be
necessary and is otherwise conformant.

**Comment by steverep** [comment]
Hi @jared-w-smith,

The latest language for this criterion, [Content on Hover or Focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus), is substantially different from that used to generate this comment, so I think all of these concerns have been addressed.

> The SC language clearly exempts user agent rendering of title text, yet the descriptions and examples refer specifically and almost exclusively to user agent rendering of title text. Because title text rendering is primarily controlled by the user agent, we believe title attribute presentation should not be covered by this SC.

Content completely controlled by the user agent is exempt in the latest language, and the description now much better matches the criterion.  I will be expanding on this description to populate the Understanding document shortly.

> The descriptions refer to enlarged mouse cursors obscuring ‘tooltip’ content and describe allowing multiple mechanisms for triggering the ‘tooltip’ content (this is already partially covered by keyboard guidelines), but the SC text addresses neither of these. There’s clearly an editorial disconnect here.

Tooltip and other hover content being obscured by large mouse cursors is now mitigated in a very different way, and there is no requirement for an alternative trigger mechanism (which is covered by 2.1.1 as you mentioned).

> Presuming that the SC is actually regarding ‘tooltip’ content obscuring triggering content (e.g., a tooltip for a link obscures the link text), this is primarily handled by the user agent or does not seem to be a disability-specific issue, but a general usability and design consideration that does not have place in accessibility guidelines. If nobody can see the triggering content, then there is no disparate experience for users with disabilities. 

First, we are now only concerned with custom content on hover or focus for this criterion, so user agent control is not an issue.  Second, the disparagement comes into play under magnification or simply with low mouse accuracy.  If I'm magnified over a trigger or set of triggers, then it may be very difficult or impossible to place the mouse pointer off the trigger, thus making it impossible to view the trigger at the magnification that may be needed.

> It also is unreasonable to require that authors provide a mechanism to turn off tooltip content when this interaction model may be necessary and is otherwise conformant.

There is no requirement to turn off tooltip content in the latest language.

**Comment by awkawk** [comment]
@jared-w-smith This SC has changed substantially since your original comment, and has hopefully been clarified in the process. Please take a look at https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus
