### ISSUE TITLE
WebAIM Feedback - SC 2.2.7 – Animation from interactions

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#258]
The impetus for this SC is to address vestibular issues (e.g., dizziness or nausea) associated with parallax scrolling (simultaneous foreground and background scrolling in different directions or at different speeds), but the language does not make it clear that scrolling is “a user action”. Clarity is needed.

This SC prescribes explicit thresholds (1/3 of the viewport and 3 seconds) with no clear data to back up the impacts of these particular values. While triggering vestibular disorders is certainly impactful to users, quality user research is needed to provide justifications for a Level A SC that would have notable impact on web/mobile design and user interaction.

This success criterion would render many common and often useful interaction models non-conformant – such as swipe animations on mobile, pop-up menu animation, focus scrolling, etc.
WebAIM would support the adoption of a clarified/improved version of this SC, but likely at Level AA or AAA unless additional, definitive research suggests a clear mapping of the defined thresholds to significant user impact.

**Comment by DavidMacDonald** [comment]
Are there any "swipe animations, popup animations" etc that are longer than 3 seconds?b Any animation less than 3 seconds is exempt. That's why it's there.

**Comment by jared-w-smith** [comment]
> Are there any "swipe animations, popup animations" etc that are longer than 3 seconds?

Longer than 3 seconds is not common, but it is common that these are "synchronized with a user action", so thus still covered.

**Comment by DavidMacDonald** [comment]
Ohhhh!   I see... yes... it's an OR statement... I propose we plug that hole... it wasn't the intention.

**Comment by nattarnoff** [comment]
@jared-w-smith while the trigger for this seems to be parallax scrolling and vestibular disorders, there are far more animations and impairments at play that this would hopefully improve. In some cases, yes, a popup or side menu can make a user ill and there should be a way to test and account for that. 

Sadly, there is very little research. As far as I can tell there is only my hastily done research in prep for my CSUN talk this year. It is far from complete and I haven't been able to find time since to start developing a further, deeper, more thorough research plan. Additionally, from my research and other anecdotes, some of which has been captured in this discussion, the overall criteria are highly variable between users. It isn't like there are simple delineations like "no vision," "low vision," "full vision" (and yes I am greatly simplifying the low vision aspect of this for the sake of argument). A person like myself can handle some aspects of animation some of the time, other aspects at other times, and no aspects at some times as well.

**Comment by DavidMacDonald** [comment]
I've proposed a revised glossary definition:

> **Significant animation:** animation which continues for more than 3 seconds, affects more than 1/3 of the viewport and may or may not be synchronized with a user action (e.g. parallax scrolling effects)

**Comment by dboudreau** [comment]
As the new manager for this SC, I'm trying to catch up on all the good things that have been said up until now. I'm in general agreement with what has been said so far, and lean towards 3 seconds and 1/3 of the viewport myself.

The issue that worries me the most so far is the lack of substantial data based on scientific research, as @nattarnoff has mentioned a few times. How can we work around this? I'm thinking we could try to come up with research of our own, maybe with the hep of vestibular.org. WebAIM has been successful in the past, conducting user research in surveys for visual impairments, could we maybe try to do the same for vestibular disorders and how they affect web use?

**Comment by nattarnoff** [comment]
I have on my dream board to actually build a more significant survey to do
just this, but my schedule hasn't permitted me to do it. I think pairing up
with VEDA (vestibular.org) is a great idea. Additionally, while I was at
CSUN, I had a professor from Syracuse approach me (I have to dig through my
stuff for their contact info yet) interest in additional research. Lastly,
on the IAAP mailing list, I discovered that the Alaska Airlines UX team was
beginning some limited research for this topic as well. We've had a few
email exchanges, but their exploration was being limited to 5-10 people.
Perhaps if they have completed that we could see what their testing
platform was like and expand the audience.

Nat

**Comment by joshueoconnor** [comment]
This issue seems to be satisfied by moving it to AAA https://www.w3.org/TR/WCAG21/#animation-from-interactions . Thank @MikeElledge. Jared we trust this is satisfactory, so we are closing.
