### ISSUE TITLE
WebAIM Feedback - SC 2.5.1 – Target Size

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#261]
The term “target” should clarify that this applies to the interactive area of a user activated link or control. The term is currently rather nebulous. “Primary purpose or function” is also vague and difficult to measure.

An exception is defined for when the link/control “has an alternative link/control whose target does meet the minimum size requirements.” Consider a superscript single character link to a footnote section at the bottom of a page. This would be a very common failure for this SC. This footnote content is readily accessible by scrolling the browser. While not as easy as a suitably-sized target for the link, this would, we believe, be more useful than requiring the author to provide “an alternative link/control” on the same page that does meet this size requirement. Consideration should be made for in-page content that is already accessible without activating the control.

Because much existing conformant web content would become non-conformant upon adoption of this SC as written, WebAIM supports adoption of this SC at Level AA with additional clarifications as noted above.

**Comment by DavidMacDonald** [comment]
Summary of requests:
- Exempt footnotes, and subscripts by saying alternative link/control where a control can be to scroll down (added exception for in page links)
- Definition for primary purpose (removed the term primary purpose, added Mandatory layout with a definition)
- Define target that it applies to the interactive area of a user activated link or control. (proposed this definition of target)

**Comment by joshueoconnor** [comment]
Note - latest version of this SC https://www.w3.org/TR/WCAG21/#target-size

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. Since your comment was logged we have changed the SC and definition of target and we believe that your concerns are addressed. First, we are changing the first sentence of the definition to:

Region of the display that will accept a pointer action, such as the interactive area of a user interface component.

Second, regarding the concern about inline content such as footnotes, we now have an exception for links in a sentence or block of text.

We hope that these address your concerns.
