### ISSUE TITLE
WebAIM Feedback - SC 3.1.9 – Extra Symbols

### ISSUE THREAD

**Issue by jared-w-smith** [w3c/wcag21#268]
While adding symbols at the beginning of critical controls may be helpful for some users, it would certainly increase cognitive load and difficulty for many other users, particularly in areas where related or generally understood symbols are not available for that critical functionality.
Terms such as “which relates to the topic”, “significant financial loss”, “deterioration in a patient’s condition or effective loss of rights”, “safety, risks, privacy, health or opportunities”, etc. are very subjective and unmeasurable.

WebAIM does not support the adoption of this SC as drafted, but may support an alternative at Level AAA that adequately addresses these concerns.

**Comment by eadraffan** [comment]
There have been no other comments about this SC, but I remain concerned that WebAIM will not support the use of extra symbols  due to cognitive overload for some users and would like to seek advice from experts in the group as to how we can improve this SC.  

I am still trying to find research that illustrates examples where use of symbols to highlight items of importance could cause overload for some web users.  

Would the term images be better than symbols?  A good example of how this SC could work has been provided by the  UK Gov Vehicle licence web page https://vehicletax.service.gov.uk/  

I agree that some of the terms used, as to when symbols/images/icons should be used, are hard to measure and this is an issue that still needs more input.

**Comment by awkawk** [comment]
@jared-w-smith This SC was not accepted into the current draft of WCAG 2.1 so will not be included in the final recommendation.
