### ISSUE TITLE
ePub SC on Meaningful sequence as applied to a set of pages.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#312]
This on behalf of the ePUB Task Force who are not familiar with our integration process for 2.1. It was at issue #162 since March 8 this year, but not proposed formally as an SC. So here it is in the proper format.

# Current versions of SC and Definitions 

- [SC for viewing](https://rawgit.com/w3c/wcag21/meaningful-set/guidelines/sc/21/meaningful-set.html) |  [SC for editing](https://github.com/w3c/wcag21/blob/meaningful-set/guidelines/sc/21/meaningful-set.html)

## Short name
Meaningful Set  

## SC Text
​1.3.X ​Meaningful Set: When the sequence in which content is presented across a set of pages affects its meaning, a correct reading sequence can be programmatically determined. (Level A)

## Or as an amendment to 1.3.2
​1.3.X ​Meaningful Set: When the sequence in which content is presented @@ on a page or across a set of pages @@ affects its meaning, a correct reading sequence can be programmatically determined. (Level A)

## Suggestion for Priority Level 
(A)
## Related Glossary additions or changes
None
## What Principle and Guideline the SC falls within.
Perceivable

## Relates to work in other TF
EPUB

## Description
see issue 162 https://github.com/w3c/wcag21/issues/162

The Understanding WCAG document addresses meaningful sequence within a single page for SC 1.3.2, but does not address the importance of the logical reading order when a document is split across multiple pages. If the sequence is not maintained across page boundaries and there isn't a mechanism to continue reading in sequence, a publication won't be readable.

This issue popped up in a recent discussion in the DPUB IG, where there was some confusion about whether WCAG has any requirements for reading order across documents, so we'd like to propose a couple of changes to the Understanding document to better highlight the applicability.

First, we propose adding the following new paragraph to the Intent section:

> If content is split across multiple pages, the reading order also needs to be preserved across page boundaries, and a means of following the sequence from page to page provided. For example, if each page contains one chapter of a publication, it must be possible to follow from the end of one chapter to the start of the next.

This paragraph could be added after the one that begins "A sequence is meaningful if the order of content cannot be changed ...".

Second, we suggest adding an additional success example:

> Example 3: In a publication split across multiple pages, the reading order is preserved across page boundaries such that the end of one document flows logically into the top of the next. A mechanism is available that allows the user, or user agent, to move from document to document in their logical sequence.

## Benefits
People who are blind will be able to tell the reading order of the book.

## Testability
Manual testing. Are the pages in a logical order programmatically or is it easy to loose one's place in the set of pages.
## Techniques
aria-current

For example, a simple change to 1.4.3 (as in the above example), might result in a response like this:
1. All existing techniques for 1.4.3
2. New technique: Providing sufficient contrast for icons

**Comment by mattgarrish** [comment]
When a publication is split across multiple pages, there needs to be a default sequence users can follow through the entire publication, and the content needs to make sense when it is followed. I really hope that one of the proposed solutions can be integrated into 2.1, as this is going to help clarify accessible practices for the Web Publications specification.

**Comment by steverep** [comment]
I agree with this conceptually, but the SC text of 1.3.2 does not make sense to extend here.  SC 1.3.2 is a requirement on the arrangement of content within a single page (i.e. at a single URI).  It's impossible to arrange content across a set of URIs, and forcing the concept of "programmatically determined" here would confuse authors way more than it already does.  The description says:

> If the sequence is not maintained across page boundaries and there isn't a mechanism to continue reading in sequence, a publication won't be readable.

I agree with that statement, but the SC text being proposed does not require that a mechanism be available to do anything.  Moreover, I don't see where @awkawk's [comment regarding why this is not just a general usability concern](https://github.com/w3c/wcag21/issues/162#issuecomment-285698562) has been addressed at all.  The only way that I can see how this disproportionately affects users with disabilities is on the pagination mechanism and the maintaining of focus.  That can be a real burden for screen reader users trying to read paginated content, so I would suggest a new proposal scoped down to that scenario.  In a sentence, it shouldn't take me 25 keystrokes to get my focus from the last sentence on page 1 to the first sentence on page 2.

**Comment by jasonjgw** [comment]
I agree with both of the concerns raised above. "Programmatically determined" seems too strong, as it would appear to require the use of a manifest linked to each resource, or a similar facility, to eanble the logical reading sequence to be established. All that is actually needed, however, is a mechanism of the kind described in the proposed explanation - capable of eanbling the user to traverse the reading sequence across pages.

Uploading my book to a server as a collection of linked HTML pages shouldn't fail this proposal on accessibility grounds.

I also agree that isolating the specifically accessibility-related issues would be a good step toward a viable proposal.

**Comment by mattgarrish** [comment]
The use of fixed layouts still sticks in my head for where this is useful. Fixed layouts will probably fail for many reasons, but there's a case that there can be a programmatically determinable sequence within each page that doesn't make sense when the pages are presented together (e.g., in a two-page spread). A sidebar might span two pages, for example, with only half the text on each. This is no issue for a sighted reader but is for someone using an assistive technology.

If we don't require meaningful sequence across pages, what makes such a practice an accessibility failure? Would you call it a failure of info and relationships? If so, that might be one way to address common cross-document sequence failures without a new SC.

I hadn't really considered an automatic bypass to continue reading, but that's an interesting point. Not specifically for epub which doesn't have the problem, but web publications look like they might shape up to have a regular web framework for vanilla browsers.

The default reading order and/or sequential links from page to page is really more of a way of achieving multiple ways, I believe. The techniques for that SC don't currently specify the ability to follow a linear path through the content, so perhaps that's where we can channel that aspect.

**Comment by jasonjgw** [comment]
I don’t think fixed layout of any kind can possibly satisfy WCAG 2.1, especially the proposal from the Low Vision accessibility Task Force that is designed to prevent unnecessary scrolling, and which can only be met by ensuring that the text is wrapped appropriately when the font size increases.

We obviously don’t write success criteria for WCAG to handle cases which are ruled out elsewhere in WCAG itself.


________________________________

This e-mail and any files transmitted with it may contain privileged or confidential information. It is solely for use by the individual for whom it is intended, even if addressed incorrectly. If you received this e-mail in error, please notify the sender; do not disclose, copy, distribute, or take any action in reliance on the contents of this information; and delete it from your system. Any other use of this e-mail is prohibited.


Thank you for your compliance.

________________________________

**Comment by WayneEDick** [comment]
I find the problem difficult to understand. Pages are arranged in
blocks with fixed positions on paper because that is necessary -paper
is inflexible.

All that is needed to understand this problem is a little self
honesty. Nobody can use enlargement that doesn't word wrap, except a
handful of really bright people with low vision. If you had to read
without word wrapping you probably couldn't keep a job. Why do you
think people with low vision have such a low employment rate. They are
forced to read inaccessible material.  If EPUB is serious about
including people with print disabilities then the enlargement with
word must be universal. Linearization is part of that.

There is no compelling reason to have multiple columns, physical
asides or any other fixed 2-dimensional arrangement of information on
a screen, except habit left over from a paper world.

People with low vision experience profound operational overhead with
fixed arrangements left over from paper.

If you want normal people with low vision to use EPUB then flexible,
linearizable content is essential.


Wayne

**Comment by DavidMacDonald** [comment]
@steverep so you have suggestions on wording... I think basically they want to ensure a blind user knows how to get to the next page, or some other page.

**Comment by WayneEDick** [comment]
This is an interesting problem. Can you give an example where a wide page
with fixed positioned objects cannot be arranged in a meaningful reading
sequence. It seems contrary to the way written literature is configured.

As a professor I reviewed lots of books. I was on the University curriculum
committee for a long time. I reviewed many courses in many disciplines
(probably for all 65 departments at one time or another.) I don't remember
encountering any content for which a meaningful reading sequence did not
exist.

To me 1.3.2 just says to make one such sequence deterministic for programs.
Isn't that enough?

Wayne

**Comment by mattgarrish** [comment]
@WayneEDick Fixed layouts are often presented as two documents side-by-side, that's what I mean by a spread. It's that this kind of layout is essentially a representation of print that makes it problematic.

To expand on my example, picture a sidebar that spans the bottom of the page. The first document has a logical sequence to it, as you'll encounter the first half of the sidebar at the end of the document. But does the second document have a logical reading sequence or not? If the second half of the sidebar is the first element but positioned by CSS at the bottom, then there technically is a logical sequence across documents. But if the second half of the sidebar is the last element, what says that it is out of sequence when you can't compare to the preceding document?

We discourage creating these kinds of documents for all kinds of reasons, but this particular case isn't specifically addressed. Yes, fixed layouts will generally fail for other reasons, but it seems like useful information to know that they also don't have a logical sequence. Otherwise, someone might judge the usability based only on whether zooming is important to them.

As it is, we'd call this practice a failure of 1.3.2 even though it only talks about inter-page sequence. But maybe this is also a failure of 1.3.1, since the sidebar is not contiguous? If so, perhaps we don't need to worry about cross-document sequencing and can focus instead on uninterrupted continuation of reading and a logical progression.

**Comment by steverep** [comment]
> I think basically they want to ensure a blind user knows how to get to the next page, or some other page.

@DavidMacDonald, I would say knowing how is the usability aspect, while executing the continuation of reading with efficiency is the accessibility issue.  For paginated content, whether within a single page or across a set, this comes down to requirements on the page navigation mechanism and managing focus.  Getting to the end of a page only to have to jump across 2 back buttons and a link for every page number just to get to the next button, then having to manually re-focus to the beginning of the next page is not good accessibility.

I don't think coming up with a set of requirements here is going to be easy either, because it may vary wildly depending on the type of content being paginated (e.g. a single article, a long book, a calendar, a slideshow, a gallery, etc.).

While I do think there's a possible SC in that realm, I'm not sure I'd weigh the priority very high at this juncture.  If you unnecessarily paginate your content, I bet a lot of people do what I do and leave your site looking for something better ;).

**Comment by nschonni** [comment]
As a non-LV I'd just like to add my 👍 to the continuous text concept.
My only only question might be is "how do paragraph/chapter breaks work"?
I think that that the minimum viable product might be "how can it be presented as just a long uninterrupted block of text"
I think the "ideal" (for me) representation of an eBook would be closer to a transcript version of a video, with no page/context breaks.
`</rant>`
For the SC text, maybe "​1.3.X When content is broken across pages without affecting meaning, a non-programitic flow format is made available for users."

**Comment by avneeshsingh** [comment]
Will like to provide a clarification for "page". Here a page refers to a document. It is not about page markup in a document. The success criteria is for meaningful reading order from one document to another. For example, meaningful reading order across set of HTML files.
In publications, multiple content documents are used to avoid practical issues of loading a huge single document.

**Comment by DavidMacDonald** [comment]
WCAG 2.1 SC boat is going to be sailing in 3 weeks. At that point the ship leaves harbour for the long journey across the ocean to Candidate recommendation. There will be no new SCs accepted after that date, only modifications to new SCs that had consensus before that date, and dropping of SCs that can't be tweaked to meet the needs of all our stakeholders.

Our meaningful sequence 1.3.2 SC requires the page to make sense, but not a set of pages (i.e., a ebook online with many URLS) which is what epub needs. Should we put this through and clean it up after August?

**Comment by jasonjgw** [comment]
Currently, I’m not aware of a good accessibility use case or rationale that applies to content which would otherwise pass WCAG 2.0 or 2.1.

I would recommend giving the issues further thought outside the 2.1 window and proposing any resulting requirement for a future version.

**Comment by awkawk** [comment]
The Working Group has not reached consensus on this proposed SC so it is deferred for future consideration.
