### ISSUE TITLE
Section headings

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#40]
<h2>SC Shortname: Section Headings</h2>
                <h3>Current:</h3>
		        <p><strong>2.4.10 Section Headings: </strong>Section headings are used to organize the content. (Level AAA)</p>
                  <p><em>Note 1:</em> "Heading" is used in its general sense and includes titles and other ways to add a heading to different types of content.</p>
                  <p><em>Note 2:</em> This success criterion covers sections within writing, not user interface components. User Interface components are covered under Success Criterion 4.1.2.</p>
                <h3>Proposed:</h3>
                <p><strong>2.4.10 Section Headings: </strong>Section headings are provided that organize the content @@(Level AA)@@ </p>
                <p><em>Note 1:</em> "Heading" is used in its general sense and includes titles and other ways to add a heading to different types of content.</p>
                <p><em>Note 2:</em> This success criterion covers sections within writing, not user interface components. User Interface components are covered under Success Criterion 4.1.2.</p>
		        <h2><a id="user-content-suggestion-for-priority-level-aaaaaa" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#suggestion-for-priority-level-aaaaaa"></a>Suggestion for Priority Level:</h2>
                  <p>AA</p>
		        <h2><a id="user-content-related-glossary-additions-or-changes" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#related-glossary-additions-or-changes"></a>Related Glossary additions or changes</h2>
		        <p>None</p>
		        <h2><a id="user-content-what-principle-and-guideline-the-sc-falls-within" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#what-principle-and-guideline-the-sc-falls-within"></a>What Principle and Guideline the SC falls within.</h2>
		        <p>Principle 2, Guideline 2.4</p>
		        <h2><a id="user-content-description" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#description"></a>Description</h2>
		        <p>The intent of this Success Criterion is to provide headings for all sections of a Web page. The current Success Criterion is included at Level AAA, however headings can be implemented as invisible by authors or hidden by a user and included when needed using personalization and semantics. The option to implement headings which are not necessarily visually displayed to any or all users, makes the suggested success criterion widely applicable and able to be included at level AA as opposed to AAA. For example, a long letter would often cover different topics, but putting headings into a letter would be strange, so they would only be visible on the user request or from personalization settings. </p><p>The main reason to upgrade the conformance level is to be consistent with user needs that are addressed across the different disabilities.</p>
		        <h2><a id="user-content-benefits" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#benefits"></a>Benefits</h2>
		        <p>Headings provide a roadmap for readers. They provide assistance in knowing what to expect and where to find information. This grouping of information within written content is helpful to guide readers and can be useful for users experiencing difficulty with language and reading comprehension. Readers with difficulty retaining focus can benefit as headings will help the user orientate themselves within the content of a page. User research shows that content created specifically for users with dyslexia tends to have well-structured text with headings, thereby reducing reading of irrelevant text.</p>
		        <p><span id="docs-internal-guid-9beb1966-7493-ec4f-40c8-08ed284fada0">It supports users who need a structure that is easy </span>to follow by providing signposts for users to find the information they need.</p>     
                <h3 id="resources2">Related Resources (optional)</h3>
                <p>Resources are for information purposes only, no endorsement implied.</p>
                <ul>
			<li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs Table (see table 5)</a></li>
			<li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background Research Document</a></li>
			<li><a rel="nofollow" href="http://webaim.org/articles/cognitive/design"><em>Cognitive Disabilities Design Considerations</em></a> - WebAIM</li>
			<li> <a rel="nofollow" href="https://rawgit.com/w3c/coga/master/issue-papers/links-buttons.html">Semantics for adaptive interfaces</a></li>
                </ul>
		<p>Example issue papers</p>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/personalization-preferences.html">Personalization and Preferences</a></li>
                </ul>
		        <h2><a id="user-content-testability" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#testability"></a>Testability</h2>
<h3>Procedure</h3>
		        <ol>
                <li><span id="docs-internal-guid-9beb1966-749b-0eb7-e278-60921282adcd">Determine the sections of a page</span></li>
		        <li>Ensure that a visible or invisible heading exists for each defined section</li>
		        <li>Each heading provides context for the section it is associated with</li>
		         </ol>
		        <h3>Expected Results</h3>
		        <ul> <li> Step 2 and 3 are true </li> </ul>
		        <h2><a id="user-content-techniques" href="https://github.com/w3c/wcag21/wiki/Proposals-for-new-Success-Criteria#techniques"></a>Techniques</h2>
		        <ul>
                  <li>H69: Providing heading elements at the beginning of each section of content</li>
                  <li><span id="docs-internal-guid-9beb1966-749d-1224-5743-5c397fe69e5a"> </span><a href="http://www.w3.org/TR/WCAG20-TECHS/G141.html">G141: Organizing a page using headings</a></li>
                  <li>Providing  headers in multimedia</li>
                  <li><span id="docs-internal-guid-9beb1966-749e-9d15-ffd4-1b6e393b7ae1">Providing </span>headings that can be made visible or hidden by the user through personalization and using semantics </li>
                  <li>Headings can be invisible or hidden by the user and can be included when needed using personalization and semantics</li>
                </ul> 
<h2> working groups notes </h2>

**Comment by LJWatson** [comment]
This feedback is based on a collective review by @SteveFaulkner @PatrickLauke @JSpellman @Sarah-Horton and @LJWatson 

We agree with the intent of SC2.4.10, but have reservations about making it a Level AA SC. 

The <a href=
"https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-headings.html">Understanding SC2.4.10</a> information states: 

"This provision is included at Level AAA because it cannot be applied to all types of content and it may not always be possible to insert headings. For
example, when posting a pre-existing document to the Web, headings that an author did not include in the original document cannot be inserted. Or, a long
letter would often cover different topics, but putting headings into a letter would be very strange. However, if a document can be broken up into sections
with headings, it facilitates both understanding and navigation." 

This proposal counters this with the following statement: 

"The intent of this Success Criterion is to provide headings for all sections of a Web page. The current Success Criterion is included at Level AAA, however
headings can be implemented as invisible by authors or hidden by a user and included when needed using personalization and semantics." 

The introduction of invisible headings would still not be possible in some circumstances. Where content is presented under a licence that prohibits alteration
or additions for example. More so if the headings could be made visible at any point through personalisation. 

The following benefit is included in the Understanding SC2.4.10 information: 

"People who are blind will know when they have moved from one section of a Web page to another and will know the purpose of each section." 

This is certainly true for content that has logical divisions within it (reports or specifications for example), but it is not necessarily so for all content
(letters and speeches for example). It could even be argued that the introduction of headings would hinder the reading experience for screen reader users
in some circumstances. 

The 1960 speech by <a href="http://lanic.utexas.edu/project/castro/db/1960/19600926.html">Fidel Castro to the UN</a> is an example (he spoke for 4.5 hours). It would be difficult to introduce headings into this content because they would be
arbitrary breaks, because the speech does not always fall into logical chunks that could be given meaningful headings, and because the presence of headings
would interupt the reading flow for screen reader users reading it from start to finish.

We suggest that this SC remain at Level AA for these reasons.
