### ISSUE TITLE
Comment on "not technology-specific" WCAG 2.0/2.1

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#407]
In it's actual version I see conflicts between "WCAG 2.1 success criteria are written as testable statements that are not technology-specific" and SC 1.3.4 and SC 1.3.5. 

In SC 1.3.4 and 1.3.5 is about "content implemented using markup languages". Together with SC 4.1.1 (WCAG 2.0) the new WCAG 2.1 would have in minimum three SC which are I think out of one main reason technology-specific: PDF is not a markup language. PDF is a page description language. It provides the possibility to add tags which can be seen as markup but this doesn't make PDF to a markup _language_. 

Another critical SC in this context is SC 1.4.13 Adapting Text. The SC says "if the technologies being used allow the user agent".  Does PDF technology allow the user agent doing adaptions required in the SC?  

Two definitions / descriptions (emphasis added, KP): 

> "The Portable Document Format (PDF) is a file format used to present documents in a manner independent of application software, hardware, and operating systems. **Each PDF file encapsulates a complete description of a fixed-layout flat document, including the text, fonts, graphics, and other information needed to display it**." (Wikipedia)

and

> "When this format was released by Adobe in 1993, it shared many of the same concepts and components of PostScript. But where PostScript was designed primarily to provide device independent consistency in print output, **PDF was focused on maintaining the visual appearance of a document onscreen**, independent of the operating system displaying it."

In discussions on github around SC 1.4.13 ([Issue 78](https://github.com/w3c/wcag21/issues/78)) the VIP-Reader was central for PDF and is mentioned in "Decription". According to the texts it seems that VIP-Reader is planned for testing procedures. According to the [description (download-page VIP-Reader)](https://www.snab.ch/en/hilfsmittel/digital-tools/the-first-pdf-reader-for-visually-impaired-people/) VIP-Reader is doing the following: 

> "The VIP PDF-Reader filters the text out of a PDF file and presents it in a user-friendly interface." 

I would think that VIP-Reader is not a usual PDF-Reader but a converter with an own user interface which displays the converted text of a PDF file. Adaptions are possible in this user interface, but I would say not in the sense of "adapt" in the glossary of WCAG 2.1. VIP-Reader is not overriding but converting, or? 

That one can do these adaptions in the user interface of this client is no indicator that the PDF technology allows adaptions in the sense of SC. Therefore I would fear that also SC 1.4.13 is not technology-agnostic but very much HTML-focused.

I think that feedback from Adobe on this is very much needed.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. At times the Working Group uses phrases such as "content implemented using markup languages" as you note, and the reason is that is some cases the Working Group has determined that a certain SC applies to technologies with specific features. This may be because there are specific markup-related that need to be attended to, or it may be used as an exception because the working group is aware of a gap in support for non-markup technologies and in order to arrive at a consensus the language is used to narrow the scope of the criterion.

In the current Editor's draft, "Text Spacing" and "Status Changes" are the only criteria remaining that employ this phrase, and in both the reason is that there is a gap in support for the requirements beyond HTML. We anticipate that this will change, and the Working Group will be able to update the criteria in response.
