### ISSUE TITLE
Proposed SC for 3.2: tell users why it doesn't work

### ISSUE THREAD

**Issue by chaals** [w3c/wcag21#423]
See also [WAI-IG discussion](http://www.w3.org/mid/CAGc5L=hkXFjvDELAMJGwmn58bO6vqV90pqS8bq_qyUz54H0RcQ@mail.gmail.com) and following messages

Problem: If a site relies on a particular technology that a user does not have or has not enabled, the user may not realise that something is not working as expected by the author.

Rough proposal: Require sites relying on a given technology to inform the user, if that technology is not applied, that the site needs it to function.

This is not entirely straightforward, since some things are easier to detect than others. Which is why it starts life as an issue and rough proposal ;)

**Comment by Ryladog** [comment]
The is somewhat like a legacy US Section 508 'Required Plug-ins''
requirement. Which wasn't a bad one at all....

**Comment by DavidMacDonald** [comment]
I hope in 2017 we won't require authors to inform users that the site relies on JavaScript, which is where the issues seems to have sprung up from.

This is an old idealogical debate... some say the page needs to work without JavaScript...

It's a little like the debate that the computer needs to work without the GUI when Windows first came out.

**Comment by jake-abma** [comment]
As ancient times are revived so once in a while so is this one still (or again) relevant... It's like old fashion that returned. When using Polymer for instance you'll see it doesn't work well with IE10/ IE11, the IE10/IE11 version a lot of Jaws users like to use because Edge doesn't work well yet with Jaws.

The result of this is that you see sites using Polymer decide to show a message you'll need another (version) of a browser. Ans yes, I also didn't see this for a decade but recently I did and it was a problem during User testing with people with a disability.

**Comment by awkawk** [comment]
A good point, but too late for WCAG 2.1 so marking "defer" and closing.

**Comment by chaals** [comment]
Fair enough. Is there an automatic process to pick up the issues that were too late, and start rolling them into a future draft?

**Comment by mraccess77** [comment]
I’ve seen it with some google maps and IR 11.
