### ISSUE TITLE
IBM comment 1 on 1.3.4 Purpose of Controls

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#426]
IBM's position is that including what amounts to a new specification inside a glossary definition is inappropriate. We do not support this SC.

**Comment by johnfoliot** [comment]
Some clarification please: is IBM objecting to this SC because of its intent, or because of the way the SC is currently constructed/worded? Would moving the list of terms that are in the normative glossary into the normative Success Criteria address IBM's concerns? What efforts could this WG take to address IBM's concerns?

**Comment by mbgower** [comment]
Sorry for the delay responding to this, @johnfoliot. For some reason my notices of new comments from Issues I'm involved with stopped getting sent to me about a month ago. I will  get an IBM response agreed on this week.

**Comment by mbgower** [comment]
>  is IBM objecting to this SC because of its intent, or because of the way the SC is currently constructed/worded? 

We're objecting to the latter. A term definition should not attempt to be a specification in its own right.

> Would moving the list of terms that are in the normative glossary into the normative Success Criteria address IBM's concerns?

How would you incorporate this list into the normative language of the SC, as you suggest? What precedent is there for that?

---

> What efforts could this WG take to address IBM's concerns?

There are myriad issues with this SC. Many have been identified and never adequately addressed in the [main issue thread](https://github.com/w3c/wcag21/issues/6). There have been additional issues raised by a number of individuals and organizations about some of them.. There are plenty of other problems with the quality of the lists of items themselves (as [identified in a separate issue](https://github.com/w3c/wcag21/issues/427)).

There are several avenues available to create a specification that can follow an appropriate process to be duly considered and adopted; some of the COGA semantics that appear in the glossary and proposed techniques were proposed for the ARIA specification, and that is an appropriate place for them to be scrutinized and vetted.

### WCAG seems to already have an avenue to adopt such a specification
For any specifications that are created (or already exist), there appears to be nothing preventing the creation of techniques in the existing 2.0 [4.1.2 Name, Role, Value](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

The wording of Purpose of Controls reads
> the conventional name of conventional form fields, conventional buttons or controls, or conventional links can be programmatically determined.

4.1.2 already contains a need for the name and role of user interface components to be programmatically determined. So once the metadata standards exist, there is an existing SC that can be used to adopt their use without the addition of any new SC.

As pointed out in [a recent issue](https://github.com/w3c/wcag21/issues/570), the approach for forms seems very achievable with the establishment of standard meta language, but the approach for links and buttons does not work as proposed since it does not use meta language but instead relies on a prescriptive use of English language labels in the actual UI.

**Comment by chriscm2006** [comment]
**Role** is not specific enough information to satisfy the intent of this success criterion. The combination of Name and Role provide "purpose" for your typical user. "Home, link". I immediately know what this thing does, and where it will take me. The problem is, for COGA users, this is not true. We need to clarify the purpose a little more. 

Role and purpose are different. 4.* Success Criteria are about how technology interacts with controls and responds to them. Does an Assistive Technology care about the distinction between a "home link" and any other menu item "link". No, of course not. But a user with a cognitive disability certainly does. Role and Purpose are fundamentally different. Allowing "purpose" to fall under 4.1.2's umbrella would convolute the intent of this SC as well as 4.1.2.

The rest of your concerns are clear to me and various solutions have been discussed throughout this SCs evolution, whether or not they're addressable is another issue. @johnfoliot thoughts?

**Comment by mbgower** [comment]
@chriscm2006  said:
> Role is not specific enough information

The requirement identifed by 4.1.2 that I am trying to highlight is "name", not the role. In an input element, authors can assign a standard meta value to the NAME attribute that can then be mapped to a user's preferred vocabulary for that meta value (i.e., the 'conventional form names' given in the definition).

Note that anchors don't have name attributes in HTML5, or any current attribute other than REL that could be used, so will need a technical solution. That could then likely be included under 1.3.1.

**Comment by johnfoliot** [comment]
> The requirement identified by 4.1.2 that I am trying to highlight is "name", not the role.
The problem with "name" is that the @name attribute can take any text string, which negates its use in machine-repurposing. The purpose and point of the current lookup list is to disambiguate a fixed list of terms (a.k.a. name values) so that they can be repurposed (i.e. "personalized") for the end user. Additionally, by providing that list & definitions, it clearly indicates which button types and link types are mandated to have this additional 'repurposing' capacity (a.k.a. metadata).

> Note that anchors don't have name attributes in HTML5, or any current attribute other than REL that could be used, so will need a technical solution.
Respectfully disagree, there are a number of methods to apply metadata to anchors and buttons, including microformats, microdata notation, and RDFa. Thus a technical solution exists today to apply specific metadata values to page elements of all kinds.

**Comment by mbgower** [comment]
> Respectfully disagree, there are a number of methods to apply metadata to anchors and buttons, including microformats, microdata notation, and RDFa.

None of which are part of the HTML5 specification, which I was specifically referring to.

**Comment by mbgower** [comment]
> The problem with "name" is that the @name attribute can take any text string, which negates its use in machine-repurposing. 

It only negates the machine repurposing to the degree the names don't follow whatever convention is being advocated. It doesn't break it. Put another way, even if someone adopted the list in its current form wholesale, there are going to be fields that are not covered by the list. That outlier field does not break the machine re-purposing. It's simply passed over by it. Same with any site that only adopts a subset.

> Additionally, by providing that list & definitions, it clearly indicates which button types and link types are mandated to have this additional 'repurposing' capacity (a.k.a. metadata).

Right, _mandated_. So that list better be backed up by a whole lot of data and scrutiny. A superficial review of the published draft makes it clear it has had no real scrutiny on such obvious things as consistent spelling. Compare that to, say, the input types in html5, which were vetted and discussed up the ying yang.

If the work had been done to get these coga attributes in the aria 1.1 spec, or html5 had incorporated some form of these, it would make it a lot easier to be advocating for this mandated list. But they didn't.  Instead we're being asked to effectively bootstrap that list _and_ dictate its use to every web author in the world. That signals "RISK" to me.

**Comment by awkawk** [comment]
Thank you for your comment. We believe that we have addressed your concerns, perhaps not ideally, but sufficiently.
