### ISSUE TITLE
IBM comment on 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#435]
IBM would like clarification on how colour gradations and pixelation are going to be handled in contrast ratio measurements.

**Comment by alastc** [comment]
Hi Mike,

I'll take an example from [a tutorial on creating icons with gradients](https://design.tutsplus.com/tutorials/how-to-create-a-gradient-icon-inspired-by-instagram-in-adobe-illustrator--cms-26592). (It is interesting to do, as you can sort-of reverse the process for testing.)

The final image is:
<img src="https://alastairc.ac/tmp/instamail1.jpg" alt="an email icon done in the style of instagram with a purple to yellow background gradient.">

Taking the white envelop outline as the 'graphical object', the top-right has good contrast, fading out to 1.8 : 1 in the bottom left.

Using an eye-dropper style contrast selector I can find the cross-over point, which is around the middle. If I 'wipe out' everything that does not meet the contrast against white, I get this:
<img src="https://alastairc.ac/tmp/instamail2a.jpg" alt="Same icon, but with the pale background deleted so it is white, leaving 2/3rds of the icon left.">

I would give that a pass, because I can still tell what it is (thanks to the gestalt principles of human perception, I'm not special!)

However, if the gradient were slightly more on the yellow side  (or the white line was under 3px and we needed 4.5 : 1) so that removing the background looked like this:
<img src="https://alastairc.ac/tmp/instamail3a.jpg" alt="Same icon, but with the pale background deleted so it is white, leaving 1/3rds of the icon visible.">

That would not pass, I can't tell what the icon is conveying.

So the principle is: If you remove the non-contrasting area, can you still tell what it is?

Does that make sense, and are there other examples you can think of that couldn't work like that?

**Comment by mraccess77** [comment]
Alistair, I generally agree with your examples, however, the location of poor contrast is important.  In your example when part of the envelope is missing in the lower right or left it has minimal effect.  However, if the low gradient at been at the top center then a low vision would not have been able to determine if the icon was an envelope or something else with a box.  So it's not just about a fraction of the missing graphic but the part of the graphic that distinguishes it from other graphics that is key.

**Comment by alastc** [comment]
>  if the low gradient at been at the top center then a low vision would not have been able to determine if the icon was an envelope or something else with a box.

I agree. I'm not sure if it is something that needs to be explicit in the SC text, but it is an implicit outcome of 'required for understanding' and graphical object.

It seems to be a good testing principle: Remove the bits that don't contrast, can you still understand it?

Taking a simple example, if you have two lines on a white background that don't contrast with each other (but do against the background), and those lines occasionally overlap, this test is a way of showing whether that is a problem (therefore should be a failure).

**Comment by mbgower** [comment]
I think it is a god testing principle, and is demonstrable. Thanks for this, Alastair. You can close the issue when you feel you have addressed Jon's comments adequately

**Comment by alastc** [comment]
Thanks Mike,

Jon, I think you're comment was agreeing with the approach? The location is indeed important!

The principle is that we simulate low vision by removing the non-contrasting areas and seeing if it is still understandable. There is a bit of subjectivity there, but I think that gestalt principles are fairly universal in human vision.

I'll close this for now, please reopen if you disagree.
