### ISSUE TITLE
Extra help

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag21#45]
<h2><strong>Extra Help</strong></h2>
<p><strong>SC Shortname: Extra Help</strong></p>
		        <h2><strong>SC Text</strong></h2>
<p>Extra Help: Provide <em>easily available beginner's help </em>or human help for <em>critical services</em> </p>
<h2><strong>Suggestion for Priority Level</strong></h2>
		        <p><br>
		          AA		        </p>
<p><br>
<strong>Related Glossary additions or changes</strong></p>
<p> <em>beginner's help</em>: Help that:</p>
<ul>
  <li>does not assume people are familiar with the Internet </li>
  <li>does not assume people use other Internet services such as email or social media</li>
  <li>does not use  Internet jargon </li>
  <li>explains the use of any design patterns other than standard HTML controls of underlined links, buttons and text boxes. </li>
  <li>uses symbols at the beginning of most paragraphs and headings</li>
  <li>gives detailed instructions on how to complete critical tasks</li>
</ul>
<p>easily available (or easily available mode or setting), one or more of the follwing is true:</p>
<ul>
  <li>can be set one time with as wide a scope as possible (such as using the standards of the OS, ETSI or GPII when available) </li>
  <li>has the option to save or to change the setting, where available interoperably, but also for the scope of the set of web pages </li>
  <li>is reachable from each screen where it may be needed and the path and the control conforms to all of this document.</li>
</ul>
<p><em>critical</em> <em>services</em> that are needed to prevent significant harm, risk or loss such as: significant financial loss, illness, injury or deterioration in a patient's condition or effective loss of rights or freedoms.</span></p>
  <p><br>
  <strong>What Principle and Guideline the SC falls within.</strong></p>
		        <p><br>
		          Principle 3, Help users avoid and correct mistakes. Guideline 3.3 &ldquo;Input Assistance&rdquo;</p>
		        <h2><br>
  <strong>Description</strong></h2>
	<p>It is hard to find a user interface design that is obvious to all users. Human help or beginners help gives flexibility and support to people who are struggling with the interface.</p>
	<p>Beginner's help is useful for people who are new to using the Internet or for people who learn slowly or have an impaired memory and therefore do not remember terms and design.<br></p>
	<p>Help content enables a user to conveniently access information needed to understand how to use the website effectively. Users who need help are usually already confused so help content should be clear and simple. </p>
               <p>Human help includes: </p>
                <ul>
                  <li> Live help option. Note: It must be easy and clear to close the window. </li>
		</ul>
                <ul>
                  <li> A phone number that will automatically call via an interoperable Voice over IP specification. </li>
                </ul>
                <ul>
                  <li> A simple contact us form. </li>
                </ul>
                <ul>
                  <li> Use available standards to get human help such as using the 0 digit on voice menu systems. </li>
                </ul>
                <h2>Benefits</h2>
                <p> This Success Criterion enables users to:
                <ul>
                  <li> access quick answers to users' questions </li>
                </ul>
		<ul>
                  <li> easily get human help</li>
                </ul>
                 <h3 id="resources2">Related Resources (optional)</h3>
                <p> Resources are for information purposes only, no endorsement implied. </p>
                <p> 
                <ul>
                  <li> <a href= "https://rawgit.com/w3c/coga/master/gap-analysis/#table-4-help-and-support"> Gap analysis Table 4: Help and support</a></li>
                </ul>
                <ul>
                  <li> <a href="https://rawgit.com/w3c/coga/master/gap-analysis/table.html">User needs Tables</a> Table 3: Entering data, error prevention &amp; recovery</li>
                </ul>
                <ul>
                  <li><a rel="nofollow" href="https://w3c.github.io/wcag/coga/user-research.html">Background research document</a></li>
                </ul>
                <ul>
                  <li><a rel="nofollow" href="https://w3c.github.io/personalization-semantics/">Semantics for adaptive interfaces</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/personalization-preferences.html">Personalization and Preferences</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/issue-papers/voice-menus.html">Voice Menu Systems</a></li>
                </ul>
                <ul>
                  <li><a href="https://rawgit.com/w3c/coga/master/techniques/index.htm">COGA Techniques</a></li>
                </ul>
  <h2><strong>Testability</strong></h2>
                <p><br>
                This Success Criterion can be tested manually.</p>
                <p><strong>Test Procedure</strong></p>
                <ol>
                  <li>Identify if this is a critical service according to the definition</li>
                  <li>If this is a critical service, confirm that there is one of the following:
                    <ul>
    <li>beginners help</li>
    <li>human help</li>
  </ul>
</ol>
Expected Results: Passes checks 1 and 2
                <h2><strong>Techniques</strong></h2>
                <ul>
                  <li>Providing a live help option. Note: It must be easy and clear to close the live help session.</li>
                  <li>Providing a phone number that will automatically call via an interoperable Voice over IP specification. This will be initiated by the user via a link similar to an embedded (Skype) number so that the user is in effect calling the support. </li>
                  <li>Providing a simple contact us form. </li>
                  <li> Using available standards to get human help such as using the 0 digit on voice menu systems. </li>
                  <li>Using COGA semantics to enable extra help on standards controls</li>
                  <li>Using COGA semantics to enable symbols</li>
		  <li>Adding icons and graphics.</li>
                  <li>Advisory: providing both human help and beginner's help</li>
                  <li>Advisory: providing beginner's help for non-critical content</li>
                  <li>Advisory: providing human help for non-critical content</li>
                </ul>
                <h2><strong>Working groups notes (optional)</strong></h2>

**Comment by mbgower** [comment]
### SC Text
>uses symbols at the beginning of most paragraphs and headings

This seems to be using a technique (use of symbols) to explain what Help is. As a definition, it should be something more generic like ‘uses non-textual cues and reinforcements for meaning’

---
### Description
>Human help includes:
-Live help option. Note: It must be easy and clear to close the window.
-A phone number that will automatically call via an interoperable Voice over IP specification.
-A simple contact us form.
-Use available standards to get human help such as using the 0 digit on voice menu systems.

These seem like methods for obtaining human help, not what constitutes human help itself. For instance, wouldn't it be better to make it something like this?
Human help can be:
1. real-time, offered with video, audio or text-based chat applications
2. delayed response, such as via the submission of questions (e.g., via a form) or via contacting a call-back service,  which then triggers a response. Notions of response time could be tackled (i.e., should responses happen within a set period?). 

> Live help option
This term isn’t defined. I’m assuming you mean an online real-time chat mechanism?

>It must be easy and clear to close the window
This is discussing the delivery mechanism, rather than the quality of the content. There was a similar blurring in the 

>A phone number that will automatically call via an interoperable Voice over IP specification. 
This seems highly prescriptive.

---
### Benefits
>access quick answers to users' questions

A request for help is not necessarily matched up with getting quick answers. There is no discussion of timing delays. If I take a week to respond for a request for assistance, it’s not giving access to quick answers.

**Comment by jspellman** [comment]
I recommend changing the handle of this SC to Help for Beginners,  (or Beginner's Help) since that describes the intent of this SC more than Extra Help.   I also suggest using "prominent" rather than "easily found", because it can be measured as a comparison to other content, rather than an absolute solution for all web pages and apps everywhere.

**Comment by jspellman** [comment]
I am volunteering to be the SC Manager for this Issue.  Here's my proposal for combining Mike's comments.  

**Help for Beginners**: If there is _critical content_ or _critical services_, provide human assistance or a _prominent_ _beginner's help_, or both. Examples of human help can be: 

a) real-time, such as video, audio, or text-based chat applications
b) delayed response, such as via the submission of questions (e.g., via a form), or via contacting a call-back service, which then responds. [Presumably in a useful time, but I don't see how we can prescribe what that time is.]

_Critical Services_ has a definition already as part of another SC, but here is a version of the definition:   
_Critical content or services_ are those that are needed to prevent significant harm, risk or loss such as: significant financial loss, illness, injury or deterioration in a patient's condition or effective loss of rights or freedoms.

I think Prominent is defined in another SC, but just in case: 
_Prominent_: A heuristic measure of how likely users are to notice a user interface component in a user interface that they are operating. Prominence can be measured in comparison with other, similar user interface components.  Prominence is affected by numerous factors, including: the number of navigation steps required, the reading order position, and visual properties (e.g. size, spacing, color). (this is re-phrasing of the ATAG definition)

Beginner's Help: Help that: 
* gives detailed instructions how to complete critical tasks
* assumes that people are not familiar with the Internet, social media, and email. 
* uses commonly used words instead of jargon. 
* explains the operation of all controls except: buttons, underlined links, and text boxes
* reinforces complex instructions with visual diagrams
* uses symbols or visual icons to draw attention and delineate the topic of paragraphs and headings

**Comment by mbgower** [comment]
@jspellman, thanks for working both critical content and services into the short text. That had been bothering me.

> [Presumably in a useful time, but I don't see how we can prescribe what that time is.]

Agreed that the time element is tough to prescribe. I suggest removing the term "quick" or any context of timing, to solve that.  On rereading this, I don't think "quick" was used in that sense anyway.

Please note that #43 Finding Help and #52 Extra help (Enhanced)  have shared language (and a lot of overlap) with this one, and some relevant comments.

 I'm going to add all the comments I submitted last fall to #32 Help, which apparently got missed, as I think it is a lot more problematic.
