### ISSUE TITLE
Comment on 1.4.14 Content on Hover or Focus

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#491]
I'm unsure how a tester can validate if the content comes from a default user agent behaviour or if it is controlled by the web page. 

It needs to also be made clear that the popup may go away for other reasons. For example, if you have a popup showing an error message and the user types into the field text which resolves the error condition then the popup should disappear as the error condition is no longer relevant. The current wording of the SC would prohibit this behaviour.

**Comment by steverep** [comment]
> I'm unsure how a tester can validate if the content comes from a default user agent behaviour or if it is controlled by the web page.

In practical terms, all the tester needs to do is determine if is coming from the HTML `title` attribute.  In more detail, it would simply be a matter of interrogating the code of the triggering element to find custom code creating the content.

> It needs to also be made clear that the popup may go away for other reasons. For example, if you have a popup showing an error message and the user types into the field text which resolves the error condition then the popup should disappear as the error condition is no longer relevant.

In that example, such a popup would not even be applicable to this SC because it would not have appeared on hover or focus but rather on input.

**Comment by jnurthen** [comment]
> In that example, such a popup would not even be applicable to this SC because it would not have appeared on hover or focus but rather on input.

Not true. The error message may well appear on focus (inline error messages). Take (for instance) an  error message which appears for required fields when focussed. This message would disappear once something is filled in. There are many other cases where this is a possibility. It should not be an error if the condition which caused the message to appear in the first place, when no longer true, causes the message to disappear.

**Comment by steverep** [comment]
> Not true. The error message may well appear on focus (inline error messages). Take (for instance) an error message which appears for required fields when focussed. This message would disappear once something is filled in.

I'm still not understanding how the trigger is on focus here; the evaluation of the field being empty is the cause.  If I fill it in and then move focus back to it again later, there's no message.

> There are many other cases where this is a possibility. It should not be an error if the condition which caused the message to appear in the first place, when no longer true, causes the message to disappear.

I do agree in principle and I think this can be either clarified as a form of dismissal in Understanding or perhaps a slight wording change.  What I'd want to be cautious about is making sure the condition under which it appears or disappears is fully controlled by the user, otherwise they may lose the ability to perceive it.  Can you offer any other examples?

**Comment by steverep** [comment]
@jnurthen, as part of a new issue #565 that I just raised, I proposed changing the 3rd bullet to:

**Persistent:** The additional content remains visible until the user dismisses it or its information is no longer valid.

I presume this would resolve your issue?

**Comment by jnurthen** [comment]
@steverep If that change gets made it will resolve the 2nd part of this comment yes. It will not resolve the first part where the tester would need to know if it is a native tooltip or a custom one.

**Comment by jnurthen** [comment]
I find the @title exception to be strange and just added to satisfy
objections. Why is it ok for some tooltips to violate all 3 of the parts of
this SC yet a custom tooltip meets 2 of 3 of the parts of the SC fails? it
is more accessible than title yet one passes but the other fails. Wouldn't
this just encourage people to use title rather than custom tooltips as they
get an automatic pass?

**Comment by steverep** [comment]
@jnurthen, I don't necessarily disagree with you, and it's a good question that applies here as well as to UI Component Contrast and Target Size, which also have similar exceptions.

For this SC in particular, I suppose the flipped question becomes: Can we basically eliminate the use of `title` for WCAG conformance?  I'm on board but there will be plenty of objectors as you said and we'd also need to eliminate a couple WCAG techniques.

In addition, the LVTF filed bugs with the browser vendors for a few things.  I'll have to go back and check to see if this was one of them.
