### ISSUE TITLE
Comment on 2.5.1 Pointer Gestures

### ISSUE THREAD

**Issue by jnurthen** [w3c/wcag21#495]
I'm concerned that this will make UIs more complex. For example when there is a dialog box which can be moved we typically provide this ability on pointer via a menu which is launched via click and hold. These functions are secondary functions which generally are not required to accomplish the task but are sometimes needed to make the page easier to use or comprehend for some users.

If in order to allow this we need to add an additional icon (and VO stop) in order to launch this menu this has consequences in making the UI more cluttered and decreasing the usability for many users.

There needs to be a definition of functionality which only requires this for functionality which is required to accomplish the task of the page not for all possible functionality which can include incidental functionality and will decrease usability for the primary task of the page.

**Comment by detlevhfischer** [comment]
How hard would it be to make those menus stick so you can move the pointer to activate an option? It could then close either on an option choice or at any second click event outside the menu? I don't understand the need for an extra icon when the click on the menu opens it. The default for native select seems to be to keep the options open (not sure if that is true for all browsers) so could custom selects not just emulate that behaviour?

**Comment by jnurthen** [comment]
There is not a native select.

 Sometimes click does something else (in a table for example it will sort
the table column). The popup menu contains other options (for example
resize, reorder etc) which can also be accomplished in other ways
(drag/drop or drag to resize for example). the popup can also be opened
using the keyboard. However adding an extra menu button to open this menu
(potentially on each column) or changing the single click function to open
the menu rather than perform the normal primary action (sort) both seem
like bad options for the usability of the primary functions of the product.

**Comment by detlevhfischer** [comment]
So if I understand correctly, you want this SC to exempt situations where controls do one thing with a short mouse click (like toggle sorting by A-Z / Z-A) and do another thing when long pressing (opening up a menu with further options)? BTW that sounds like  construct that may be beneficial for some, but could also be quite problematic for other users (discoverability, consistency). If we exempt that (for 'incidental functionality'), authors could go further and design it so that a long press brings up the menu, but if you hold longer then three seconds it opens up a popup with still further options. Where do we stop?
So it seems there are 3 options:
- WCAG 2.1 is stricter than  2.0 so your custom controls would meet 2.0 but not 2.1 unless they open by default on a single short click (I don't think an extra control to open them would be practical) or you separate a toggle sort button from the menu (which sounds useful to me, but would add an extra tab stop)
- We manage to introduce a convincing distinction between essential and incidental functionality as you suggest
-  We retire the SC because there are custom behaviours that would fail under the new SC - there just doesn't seem much scope to chisel away at it, like exempting long presses, I think

**Comment by joshueoconnor** [comment]
@detlevhfischer  I don't think this is ready for review yet, and may get further comments/feedback -@jnurthen before we do make any group review on this, can you comment on the options that @detlevhfischer has suggested? Do they work as exceptions or can they be simplified? Thanks

**Comment by detlevhfischer** [comment]
@jnurthen 
At TPAV the text of the SC has been changed to 
> "All functionality which uses multipoint or timed gestures for operation can be operated with an untimed single-pointer activation, unless a multipoint or timed gesture is essential."

Does that remove your concern? Not sure if the behaviour you would like to exempt (long press calls up another action that click, which would fall under timed gesture) would qualify as 'essential'.

**Comment by awkawk** [comment]
We have clarified the SC, definition, and understanding content will be added.
