### ISSUE TITLE
Comment on 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#522]
Does there need to be any exception provided for when authors include screen shots or other graphical replications as part of the content?
I believe that if a 'pasted' image is considered a single object, then all that would be required to meet the wording and intent of this SC would be for the author to provide a border around any such object that had no delineated edge (such as a screen shot, which often just has the white of the page background as its edge. This could be captured as a technique.

**Comment by alastc** [comment]
I had thought this would come under the 'essential' exception, a bit like an image of a landscape, or group of friends picture typically posted on facebook. 

I can certainly add that example to the understanding document if that is agreeable?

**Comment by goodwitch** [comment]
+1,  I think it would be helpful to include examples of these exceptions in
the understanding doc

G

glenda sims  |   team a11y lead   |    deque.com    |    512.963.3773
*web for everyone. web on everything.* -  w3 goals

[image: IAAP International Association of Accessibility Professionals:
Certified Professional in Accessibility Core Competencies (CPACC)]
<http://www.accessibilityassociation.org/certification>

**Comment by steverep** [comment]
Yes, screenshots should be an explicit part of an exception, but not every screenshot must be justified as "essential".

**Comment by alastc** [comment]
Hi Steve, I guess the phrasing should be something like:

If the fact it is a screenshot is intrinsic to the graphic then it is essential to convey that. For example, highlighting how a website layout is displayed. However, simply taking a screenshot of text or another graphic does not make it essential.

**Comment by steverep** [comment]
@alastc, I completely agree of course.  When I suggested something like "depictions of reality", I was trying to include screenshots as well.  In other words, the purpose of the screenshot should be to depict the reality of what's on a screen.

My overall point is that it seems like an author now has to evaluate every single graphic they put into the content as either passing with good contrast, or being "essential", which diminishes the rare nature that type of exception should convey.  We're aware of all types of things that ought to be exempt because of their inherent nature, so we need to explicitly put them in the SC.

**Comment by awkawk** [comment]
We will include these image types as examples under "essential" in the understanding docs.
