### ISSUE TITLE
Comment on complementary use of graphics in 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag21#523]
[Graphics Contrast](http://rawgit.com/w3c/wcag21/correct-use-of-essential/guidelines/index.html#graphics-contrast) seems to be concerned with ensuring that meaningful graphics are discernable. But what about when the graphic serves as a complementary visual to text information. In example, if an author uses a cation icon that combines a graphical exclamation mark with the text (not image of text) "attention," then there is a persistent visual cue in the form of text for the user.
It would be my argument that in such a situation, the phrase "are necessary for understanding the content or functionality" would no longer apply and the graphic would not need to meet the required contrast.
If that is the feeling of the SC manager, then I think that scenario should be clarified in the Understanding document. If that is not the interpretation of the SC manager, then I think this case needs to be addressed.

**Comment by awkawk** [comment]
cation = caution?

**Comment by detlevhfischer** [comment]
As we have comments from groups representing people with cognitive disabilities that little of what has been proposed has made it into WCAG 2.1, it might be worthwhile considering that we keep good contrast requirements for those cases, too. 
For people with reading difficulties, having an icon which has sufficient contrast would be important. (Needless to say it is a usability gain for everyone.) I know of many cases where contrast of such additional icons is below 3:1 because the designers found it more pleasing that way, but I think it would be good to make this reqirement general. For the likes of IBM & Oracle, how much redesign effort would it be to swap around the icons used for more contrasty versions in their next software release?

**Comment by alastc** [comment]
Hi @mbgower,

That is my feeling, does the top of the understanding address this comment now?
https://rawgit.com/w3c/wcag21/graphics-contrast/understanding/21/graphics-contrast.html
(Under the 'required for understanding' heading.)

**Comment by awkawk** [comment]
@mbgower Does @alastc's response address your concern, so we can close this issue?

**Comment by mbgower** [comment]
YEs, that makes sense. I'll review and closed

**Comment by steverep** [comment]
@alastc, I assume you are referring to the following bullet in the draft Understanding:

> The information is available in another form elsewhere on the page, or linked from the page

And I think this is an extremely dangerous thing to state.  It raises just enough subjectivity to possibly diminish the point of this SC for important graphics.

Take simple bar, line, pie, etc. charts as an example.  Would you say that providing tables of the raw data absolves the need for a chart to meet the contrast requirement?  I certainly do not think it should since the entire point of a graph is to discern trends and relationships that simply cannot be conveyed through text.

**Comment by alastc** [comment]
Hi @steverep, that’s a tricky one, we currently do accept a data table as an alternative for screenreader users.

If the table had a suitable caption calling out the trends / conclusions, I’d be happy with that as an alternative in general. (Perhaps not in scientific or educational scenario though.)

I see two ends of the scale for this:

1. A simple graphic has a text label nearby. 
2. A complex graphic (e,.g. chart) is conveying information through the combination of graphic objects.

As a developer considering all the accessibility use-cases, I’m worried that we add a lot of overhead with both alternatives (required for non-visual access) and contrast of complex graphics. Is it unreasonable to have an alternative in text for such graphics? This helped avoid objections from others.

**Comment by steverep** [comment]
@alastc, there's a very big difference when talking about alternatives for screen readers because those must be text in order to be consumed.  So while I'd never advocate omitting the programmatic `alt` text, deeper descriptions in the caption and body are to be expected in good technical writing, and it amounts to equivalence inasmuch as a screen reader can handle.

The key is that last part though.  People misconstrue a "text equivalent" as "equivalent", and it most certainly is not.  Tactile graphics exist and are used more and more by blind and low vision learners for a good reason: a picture truly is worth a thousand words.  And pictures with good contrast can level the playing field for many with low vision without the tactile need.

**Comment by alastc** [comment]
Sure, but the line in the sand we have for this is "required for understanding".

How would you phrase that example to say whether there was an equivalent elsewhere on the page that fulfilled the same meaning?

**Comment by steverep** [comment]
> Sure, but the line in the sand we have for this is "required for understanding".
How would you phrase that example to say whether there was an equivalent elsewhere on the page that fulfilled the same meaning?

Well, I'm arguing that often the same meaning is not fulfilled by text.  But in the edge cases where it could be or other high contrast graphics fulfill the meaning, I would say it goes back to the conformance requirements... and I don't feel like opening that can of worms here :).

**Comment by alastc** [comment]
How about we remove the 'link to other page' aspect, is that a reasonable compromise for now?
