### ISSUE TITLE
JR comment on Purpose of Controls

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#546]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* What’s a “conventional name”? I’m assuming they are the bold items listed in the definitions for conventional links, etc.  (“compose”, “next”, “delete”). But, how are these to be communicated (e.g. will ARIA include this vocabulary?) 
* Also, what’s the significance of “content implemented using markup languages”? It’s on 3 SCs in the list. If it’s significant, should it be on more? 
* Unless ARIA includes the mechanism I don’t see this being ready for WCAG.

**Comment by jake-abma** [comment]
Hi Jan

Thank you for your feedback!

- You are correct, the conventional names are the  items listed in the definitions. We will try and clarify that in the understanding section and the techniques. There is an [ARIA module WD](https://www.w3.org/TR/personalization-semantics-1.0/) to support this and other methods include autocomplete and microdata.

- We have limited the scope to mark up languages like HTML as we do not know how to support this in all formats such as PDF. If you want you can look at our [draft techniques at COGA Techniques ](https://docs.google.com/document/d/1YiknHDDDdKBdwVTEpxwUpyCaQL_tnpp9CfDlFjCq16E/edit#heading=h.n8sq8t3ebanu)

By the time we leave CR we are committed to all SC have  working websites and implementations in a few different platforms (or they will be removed from the final draft). Please see [WCAG 2.1 CR Exit Criteria](https://www.w3.org/WAI/GL/wiki/WCAG_2.1_CR_Exit_Criteria) for the details.

We hope that answers your concerns, if not please feel free to open a new issue.

**Comment by jake-abma** [comment]
Hi @JanRichards

Thank you for your feedback!

- You are correct, the conventional names are the  items listed in the definitions. We will try and clarify that in the understanding section and the techniques. There is an [ARIA module WD](https://www.w3.org/TR/personalization-semantics-1.0/) to support this and other methods include autocomplete and microdata.

- We have limited the scope to mark up languages like HTML as we do not know how to support this in all formats such as PDF. If you want you can look at our [draft techniques at COGA Techniques ](https://docs.google.com/document/d/1YiknHDDDdKBdwVTEpxwUpyCaQL_tnpp9CfDlFjCq16E/edit#heading=h.n8sq8t3ebanu)

- By the time we leave CR we are committed to all SC have  working websites and implementations in a few different platforms (or they will be removed from the final draft). Please see [WCAG 2.1 CR Exit Criteria](https://www.w3.org/WAI/GL/wiki/WCAG_2.1_CR_Exit_Criteria) for the details.

We hope that answers your concerns, if not please feel free to open a new issue.

**Comment by JanRichards** [comment]
I'm concerned that as a brand new requirement requiring a new markup technique (and at AAI, this requirement will have the effect of rendering every form on the web that is currently WCAG AA compliant, no longer compliant.

**Comment by yatil** [comment]
@JanRichards WCAG 2.1 introduces new requirements, some of those will not be met by WCAG 2.0 compliant sites. This is to be expected. They will still be WCAG 2.0 compliant and can then make efforts to become WCAG 2.1 compliant as well.

**Comment by jake-abma** [comment]
Hi @JanRichards,

Is the feedback from @yatil clear for you and removes the concern here?

If not please let us know and we’ll be happy to answer.

**Comment by JanRichards** [comment]
Maybe I'm not understanding. Is it possible to meet this requirement using only HTML or is use of the new ARIA module also required?

**Comment by johnfoliot** [comment]
Hi Jan,
The goal is to attach metadata to the specific controls. *How* authors achieve that will be open: once Personalization Semantics becomes a Rec, you will be able to use that technique. Another technique will be to use MicroData (another W3C Rec) and schema.org values (I've been chatting with some folks there already).
The current Exit Criteria mandates that any SC be implementable upon publication, with a minimum number of examples in the wild. For that reason, I've been extremely focused on  viable implementation strategy, and am convinced that the MicroData / schema.org solution will fit our needs immediately.
JF

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jan Richards <notifications@github.com> Date: 11/17/17  6:06 PM  (GMT-06:00) To: w3c/wcag21 <wcag21@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [w3c/wcag21] JR comment on Purpose of Controls (#546) 
Maybe I'm not understanding. Is it possible to meet this requirement using only HTML or is use of the new ARIA module also required?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/w3c/wcag21","title":"w3c/wcag21","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/w3c/wcag21"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JanRichards in #546: Maybe I'm not understanding. Is it possible to meet this requirement using only HTML or is use of the new ARIA module also required?"}],"action":{"name":"View Issue","url":"https://github.com/w3c/wcag21/issues/546#issuecomment-345398779"}}}

**Comment by JanRichards** [comment]
Hi John. I guess I'm just surprised that we'd be in a situation in which a simple plain HTML form (first name, last name, email) couldn't meet WCAG 2.1 AA without using a technology outside of HTML. But, then again I haven't been following the group closely over the past couple of years and so maybe this has all been discussed and agreed.

**Comment by johnfoliot** [comment]
Hi Jan,
There is a fairly well known web page out there that prominently features a submit button tagged "I'm feeling lucky". For some COGA users, that could be confusing. :)
Additionally, the use of autocomplete in forms improves accuracy significantly for users with spelling and language issues (dyslexia, etc.). So while basic forms can often appear easy to many users, this SC expands the size of that user-group by making them even easier. Given the number of major web sites today who are already using the @autocomplete attribute, this feels like a fairly simple and light-weight ask on authors.
Adding metadata to the list of User Interface Controls will be the second half of this SC. We still need to review the list of those terms to ensure we have the right ones (as well as find the balance between critical vs. nice to have for each term).
JF
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jan Richards <notifications@github.com> Date: 11/18/17  2:56 PM  (GMT-06:00) To: w3c/wcag21 <wcag21@noreply.github.com> Cc: John Foliot <john.foliot@deque.com>, Comment <comment@noreply.github.com> Subject: Re: [w3c/wcag21] JR comment on Purpose of Controls (#546) 
Hi John. I guess I'm just surprised that we'd be in a situation in which a simple plain HTML form (first name, last name, email) couldn't meet WCAG 2.1 AA without using a technology outside of HTML. But, then again I haven't been following the group closely over the past couple of years and so maybe this has all been discussed and agreed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/w3c/wcag21","title":"w3c/wcag21","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/w3c/wcag21"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JanRichards in #546: Hi John. I guess I'm just surprised that we'd be in a situation in which a simple plain HTML form (first name, last name, email) couldn't meet WCAG 2.1 AA without using a technology outside of HTML. But, then again I haven't been following the group closely over the past couple of years and so maybe this has all been discussed and agreed."}],"action":{"name":"View Issue","url":"https://github.com/w3c/wcag21/issues/546#issuecomment-345470607"}}}

**Comment by JanRichards** [comment]
Hi John. Thanks for the explanation. Cheers.

**Comment by mbgower** [comment]
I don't think the question has been addressed.
The Google home page has a number of obvious challenges/failures, the two most obvious of which can be dealt with using existing 2.0 requirements and plain old html.

1. The input has no label.
1. There is no instruction to clarify the difference between the Google Search and the I'm Feeling Lucky buttons.

Once those two 2.0 issues were resolved, we could then see whether anyone thinks the page is unclear. And, once Purpose of Controls was implemented and was leveraged by someone, we could see whether the results were of benefit.

But what attribute value would you place on that submit button to clarify its purpose? "submit"?
"I'm feeling lucky" not only submits the form but returns only the top result and automatically loads it.

I believe a common implementation that might come out of Purpose of Controls is an AT/user relabelling controls based on the attribute value to an easily understood standard meaning. Giving this button the designation of "submit" means a user relying on a simplification of content would then see two Submit buttons on the page _and_ not have an ability to distinguish between them.

I don't see that Purpose of Control is going to resolve issues with the dual button Google home page. To me, pointing out Google's home page as an example strengthened Jan's case.

**Comment by awkawk** [comment]
Thank you for your comment. We have an updated draft that does not include the "conventional name" language. We think that the latest version will be more easily understood.
