### ISSUE TITLE
JR comment on Character Key Shortcuts

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#556]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

* Does this rule out the simple use of “accesskey” or is the idea that the content is doing something itself with Javascript? 
* If simple use of “accesskey” is ruled out, I’d disagree.

**Comment by mbgower** [comment]
The [definition of character key](https://w3c.github.io/wcag21/guidelines/#dfn-character-keys) is:
> **character key**
  single printable Unicode code point, any keyboard character that is printable, i.e. letters of the alphabet including capitals, punctuation, numbers, and symbols
   Note that the Space and Enter keys, which return empty spaces rather than characters, are not character keys.

An accesskey has a modifier, so they are excluded from the definition of character key.

**Comment by mbgower** [comment]
@janrichards, I am closing the issue. If you do not feel I have fully addressed your Issue, please feel free to reopen and post a new comment.

**Comment by JanRichards** [comment]
Agreed. Thanks.
