### ISSUE TITLE
JR comment on Target Size (No Exception)

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag21#559]
[Filed by email 14 October 2017](https://lists.w3.org/Archives/Public/public-agwg-comments/2017Oct/0001.html) by @JanRichards

So use of plain text links (<a>) is prohibited? If so, I’d disagree.

**Comment by awkawk** [comment]
The use of plain text links is not prohibited, but the text size needs to be larger or links need to have sufficient padding to make the target area large enough.

**Comment by JanRichards** [comment]
My concern is that plain old HTML links <a> where I haven't specified any CSS will fail the SC because they typically aren't rendered 44 CSS pixels tall ( I think the default of most browsers is around 20px). I don't think I should have to write CSS for my my plain old HTML page to pass WCAG. I haven't constrained anything, so users are free to change their default font size, pinch zoom, etc. to get a bigger target if they need one.

**Comment by steverep** [comment]
@awkawk, an important qualifier to adding extra padding is that this only makes sense when the link is in a block or line by itself.  If it's inside a sentence, it would make the text difficult to read.  (I'm assuming this is not combined with negative margin, which results in much more serious problems.)
