### ISSUE TITLE
WHICH vs  THAT    Grammatical - but some with normative implications    

### ISSUE THREAD

**Issue by GreggVan** [w3c/wcag21#609]
In a number of places in WCA 2.1  we use WHICH  when we should use  THAT.  

This is important because  "WHICH" means the phrase is just giving additional information that can be deleted from the sentence without changing its meaning.

"THAT" means the phrase is 'restrictive' and must be part of the sentence. Deleting it changes the meaning of the sentence.       

In grammar terms

> THAT should be used to introduce a restrictive clause.
> WHICH should be used to introduce a non-restrictive or parenthetical clause.
> 
> A restrictive clause is one which is essential to the meaning of a sentence – if it’s removed, the meaning of the sentence will change. For example:
> 
> Chairs that don’t have cushions are uncomfortable to sit on.
> Card games that involve betting money should not be played in school.
> To our knowledge, it is the only body in the solar system that currently sustains life…

> A non-restrictive clause can be left out without changing the meaning of a sentence. Non-restrictive clauses are either in brackets or have a comma before and after them (or only before them if they come at the end of a sentence):
> 
> Chairs, which are found in many places of work, are often uncomfortable to sit on.
> I sat on an uncomfortable chair, which was in my office.
> 

In other words,   if you use WHICH,  the phrase can be left out and it doesn’t change the meaning.   

- You can use tom's car,  which is blue.      "which is blue" can be left out without changing the meaning of the sentence (just the amount of information in it)

- you can use tom's car that is blue.          Means you can only use tom’s blue car — not his silver one. 

HERE IS WHERE WE USED WHICH CORRECTLY 
> It also gives information about how to make conformance claims, which are optional. 

HERE IS WHERE WE USED WHICH INCORRECTLY 
for example  WCAG 2.1 uses 
            "Functionality which can be operated... “   
 when it should be    
            "Functionality that can be operated... 

the phrase  “can be operated”  is not extra info — but a restrictive phrase that is important to what we mean --  so we must use  THAT. 

Attached is a copy of the  WCAG 2.1  with all of the places marked where WHICH should be THAT

Not too many but more than a few.  
They are highlighted  and marked with change tracking.  

[Web Content Accessibility Guidelines (WCAG) 2.1.docx](https://github.com/w3c/wcag21/files/1539633/Web.Content.Accessibility.Guidelines.WCAG.2.1.docx)

**Comment by mbgower** [comment]
I think those changes are fine as editorial, and some folks will find it clearer to use "that" in each case you outlined. 

I'd make the argument that it is the punctuation that far more clearly determines whether or not the information is indicative of being in restrictive apposition. The SC language made it through heavy scrutiny without anyone inferring these uses of "which" _weren't_ restrictive.

For instance, given the absence of a comma, I think it's a lot harder to argue that things like the definition of down-event: "platform event which occurs when the trigger stimulus of a pointer is depressed" is non-restrictive simply due to the use of "which". You're unlikely to find anyone who voted on it who had the interpretation that _any_ platform event is a down event.  

For the occurrences you caught in the bullets of Accessible Authentication where the use of the comma _and_ the use of "which" clearly suggests it is non-restrictive, that's a critical ones to tackle. I _think_ those "which" phrases were clearly meant as elaboration on what was meant by "alternative essential steps" and should be restrictive. The SC language had been undergoing constant proposed changes since this first version, and now that that version has been brought back due to a lack of consensus,  I think it should be  run by the COGA Task Force to confirm this would be welcomed entirely as editorial clarity.

**Comment by Ryladog** [comment]
+1 to Greggs statement

**Comment by JohnRochfordUMMS** [comment]
Hi Gregg, Mike, and All,

I am the Accessible Authentication SC manager. I have decided to create a superhero to tackle this important issue. I can’t decide whether to call him “WHICH Man?” or “THAT Man!”. I’ll ponder it while I address your concerns in the next version of the SC.

John

John Rochford<http://bit.ly/profile-rj>
UMass Medical School/E.K. Shriver Center
Director, INDEX Program
Instructor, Family Medicine & Community Health
www.DisabilityInfo.org
Twitter: @ClearHelper<https://twitter.com/clearhelper>

Confidentiality Notice:
This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary, and privileged information. Any unauthorized review, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please contact the sender immediately and destroy or permanently delete all copies of the original message.

**Comment by detlevhfischer** [comment]
Here is an article by a noted linguist on the assumption that restrivtive clauses should use 'that' instead of 'which'.
https://www.chronicle.com/blogs/linguafranca/2012/12/07/a-rule-which-will-live-in-infamy

For which-hunting in a historical context, see
http://languagelog.ldc.upenn.edu/nll/?p=20968
Have fun.

**Comment by mbgower** [comment]
@JohnRochfordUMMS 
> I have decided to create a superhero to tackle this important issue. I can’t decide whether to call him “WHICH Man?” or “THAT Man!”

Wow, who would have thought the working group process would give me my first chuckle of the day!

Having been brought up and schooled on a near-biblical regard for _Modern English Usage_, I'm a little sheepish to be siding against Fowler on this one; however, I'm going with Detlev's reference:

> Punctuation suffices to distinguish restrictive from nonrestrictive relatives.

To emphasize, I think Gregg's suggested changes are fine -- and I think he's ID'ed an issue John is going to have to don his superhero to resolve for Authentication -- but I don't think replacing the other occurrences of "which" is _necessary_.

**Comment by GreggVan** [comment]
please clarify what you mean. 

If you mean that the changes I suggested in the attached DOC file  - with edit tracking -  that is good.     It ain’t good to use understandable but bad grammar in a standard if we can help it. 

If you mean that OTHER uses of WHICH in the document should not be changes - that is ALSO good.    Those were correct uses of which.

As you point out, punctuation is important — and there were a couple of commas that needed to be removed — but I pointed them out in a separate comment.  I think there was only one place where they were present and should be removed — but not sure. 

Thanks

G

**Comment by awkawk** [comment]
(Official WG response): 
Thank you for your comment.

We are happy to make the changes from "which" to "that" for the WCAG 2.1 SC, glossary definitions, and within the "common purposes" section in order to make the guidelines more clear. We cannot change all of the suggested items, including boilerplate text and text within WCAG 2.0 glossary items. The main change needed to make it clear that sentence parts now starting with "which" are restrictive clauses is dropping the comma. The comma will be removed in cases where we need restrictive clauses.

Will be reflected here: http://rawgit.com/w3c/wcag21/master/guidelines/index.html
