### ISSUE TITLE
Success Criterion 2.6.1 Motion Actuation: Consider separating device motion and user motion into two SC to make guidance easier to understand and to prepare for future SC under 2.6

### ISSUE THREAD

**Issue by SuzanneTaylor** [w3c/wcag21#621]
There's a third type of similar functionality that is not mentioned here. That is where a device is observing, and the user is positioning **other** objects or devices, and the user's motion is irrelevant, but the position of those **other** objects or devices has meaning and results in the application. I think that this should wait until a future version of the guidelines, because there is a lot of work to do on this. When that happens, it should probably be in a separate SC, so that it doesn't make SC's more difficult for people to read. [Note, though, this is already emerging quickly in a simple form called "target" AR.]

Considering that that case should be in a separate SC in the future, and that requirements and techniques for user motion and device motion might evolve (in different ways) to more direct interaction with AT, it might make sense to separate out device motion and user motion into two SC now. Most developers will only be working with one case at a time, so keeping them separate would make the guidance easier to understand, and probably be more logical once other, similar, SC are added later.

**Comment by joshueoconnor** [comment]
Relates to https://www.w3.org/TR/WCAG21/#motion-actuation

**Comment by joshueoconnor** [comment]
I've a question @SuzanneTaylor when you say:

> That is where a device is observing, and the user is positioning other objects or devices, and the user's motion is irrelevant, but the position of those other objects or devices has meaning and results in the application

Do you mean that when the combination of user interaction and device observation may in some cases result in the instantiation of a new application?

**Comment by SuzanneTaylor** [comment]
It could be a situation where an application is launched based on observation, perhaps in a smart home, noting who is home and launching reminders, or something like that. But I was thinking about games that are emerging now where you are positioning cards, or dice, or other game pieces and then you view those through your device camera, and they come to life, and different things happen based on placing items near each other or in specific arrangements. So it is neither the user's motion or the device's motion that matter, but the location of the playing cards or other objects, which the user or users move around.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. You raise two issues - one is splitting device motion and user motion into separate SCs, the second is making us aware of a third type of similar functionality, that of motion / events in the field of view of the device (device is observing). We agree that this is a separate issue and potentially, a separate SC. In this SC, the issue is active, purposeful user input. We believe that the SC Motion Actuation addresses broadly issues common to two scenarios: firstly when the user moves the device itself (shaking, titling, panning) and secondly, when the user motions towards the device, i.e. carries out gestures aimed at actuating functions. We think that both scenarios can therefore be treated in one SC.

We have updated the SC text and the Understanding text to clarify that input caused by the user moving through space, and situations where the device is observing anything other than purposeful user inputs, are not covered by this SC.

As to your suggestion to separate out device and user motion, we will mark this issue as "defer" to ensure that it is reviewed at an appropriate time in the future.
