### ISSUE TITLE
2.6 Suggested Guideline Text

### ISSUE THREAD

**Issue by SuzanneTaylor** [w3c/wcag21#622]
Could use **"Make functionality available without requiring real world motion or positioning."** This covers not requiring users to, for example, hold the phone up high, position the phone in landscape, move the phone in a specific way, etc. It is also able to cover situations like those discussed here https://github.com/w3c/wcag21/issues/621 for future SC
OR
**"Require the least amount of real world motion or positioning needed for functionality."** 
This has the same advantages as the text above, but it leaves the door open for some *future* SC that require adjustments to the sensor-based functionality to make it easier to use, as well as requiring alternatives. For example, for inputs for AR and VR, wheel chair users (and many others) can often be accommodated by just moving the target objects downwards. If the requirement is always to just provide a full alternative that doesn't require motion, the full experience for wheelchair users (and many others) might be unnecessarily less engaging. And, once new AT appears for this, even more people with mobility impairment might also prefer that type of accommodation, rather than simple replacement. (AT down-the-road might remap an app's understanding of where the phone is to the position of a virtual phone, but control of that virtual phone might easiest when restricted to some extent.) It's kind of similar to providing alt-text for small blurry images. For some users, a better image would be best, but the guidelines require alt-text. However, if AR and VR become significant, this situation might be the difference between participation and exclusion (through exceptions) from entire categories of software, which is not the case for alt-text/images! Techniques in addition to replacement should at least be mentioned as optional best practices in the understanding document.

**Comment by awkawk** [comment]
Thank you for your comment. 

We have updated the Editor's draft with text for guideline 6.2 "Ensure that device sensor inputs are not a barrier for users." (see http://rawgit.com/w3c/wcag21/master/guidelines/index.html#additional-sensor-inputs)

You describe usage scenarios where input happens not via a particular user motion, but via the position or orientation of the device. This issue is likely to become more important with the spread or AR / VR use scenarios. However, we believe it can be separated from the use case of motion actuation where motion is relative to the device and the exact position (e.g. on the z-axis, distance to ground) seems less relevant. The case of orientation (no position lock unless by user choice, content adapts to user-chosen orientation) seems already addressed by the SC 2.6.2 Orientation.

You raise an interesting issue when you talk of alternatives other than user interface controls that still use motion but adapt in other ways (e.g., by lowering AR / VR objects for wheelchair users), motivated by the aim to not negate the full experience for wheelchair users (and many others). While different accommodations are certainly useful and should be encouraged, they would not negate the need for a means of input that works with keyboard and pointer interfaces. (An analogy might be sign language: Having a sign language version of a video talk is great, but it does not negate the requirement for captions.) You make the point that in the future, the availability of those other accommodations might be the difference between participation and exclusion (through exceptions) from entire categories of software. Requirements for alternative accommodations would be a good subject for a future SC as these technologies become more mature and widespread. We are open to suggestions to include additional techniques as optional best practices in the understanding document. Can you provide a description and examples that could be used?

**Comment by SuzanneTaylor** [comment]
An analogy I like to use is if there is a roller coaster that starts at point A, and ends at point B, having an accessible doorway from point A to point B is not the same as having access to the roller coaster :-)  
This is just starting to play out in physical places. Some of it is actually ADA! And some is definitely game accessibility.  It's not clear where the line is for what could fall into WCAG or your future AG release. 
But, I'll definitely check back - thanks for all the great work on WCAG 2.1!
