### ISSUE TITLE
Success Criterion 1.4.13 Content on Hover or Focus

### ISSUE THREAD

**Issue by MichellanneLi** [w3c/wcag21#630]
> When pointer hover or keyboard focus triggers additional content to become visible, the following are true:
> 
> **Dismissable** A mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an input error;
> **Hoverable** If pointer hover can trigger the additional content, then the pointer can be moved to hover the additional content;
> **Persistent** The additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.
> Exception: The visual presentation of the additional content is controlled by the user agent and is not modified by the author.

I find this really confusing and would like some examples to illustrate these criteria. These examples might resolve the following questions:

If there must be a mechanism to dismiss content without moving the pointer or keyboard focus, what might that look like? Most mechanisms to dismiss content ask that the user click on a button, which requires moving the pointer or keyboard focus.

What is the benefit to being able to hover over additional content that only appears on hover? There are use cases in which it makes sense (such as a dropdown that appears on hover in a nav), but I feel those are exceptions rather than the rule.

**Comment by awkawk** [comment]
(Official WG response):
> I find this really confusing and would like some examples to illustrate these criteria.

The Understanding document is in the process of being updated, and will offer examples and clarity. The current draft provides some explanation and [Examples](https://w3c.github.io/wcag21/understanding/21/content-on-hover-or-focus.html)

> If there must be a mechanism to dismiss content without moving the pointer or keyboard focus, what might that look like?

The normal mechanism for dismissing any kind of overlay is the Escape key; if that is implemented, this first bulleted requirement is met. Note that the wording of the SC does not prevent an author from adding in a mouse-equivalent affordance for this (such as simply moving away from the trigger/new content or hitting a close button displayed as a ‘x’ in the upper right corner of the overlay). The SC simply requires that there be a method that does not involve moving the mouse.

> Most mechanisms to dismiss content ask that the user click on a button, which requires moving the pointer or keyboard focus.

> What is the benefit to being able to hover over additional content that only appears on hover?

The specific reason for a requirement to dismiss the on-hover overlay without moving the mouse, involves low vision users or users with reduced fine motor skills. Low vision users with a substantial level of magnification have a limited viewport. If they accidentally trigger new content with hover, they need to be able to dismiss that new content without losing their current point of regard. Otherwise, they are put in the situation where they must move their entire viewport away from the location they wished to interact with in order to dismiss the new unwanted content. After re-orienting themselves back again after the new content disappears, they then may accidentally trigger the hover again, repeating the same experience. Similarly, a user who cannot easily control the mouse and so is more prone to accidental triggering of on-hover content, needs a method of easily dismissing that is not mouse based.

As will be made clear in the Understanding document, this SC is not recommending or encouraging the use of On Hover or On Focus as the trigger for displaying new content. This is considered a poor interaction by many, since users may easily inadvertently trigger new content. However, where an author elects to employ On Hover as a trigger, this SC places requirements on the implementation which make the resulting experience more accessible.
