### ISSUE TITLE
Comment on 1.4.12 Text Spacing

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#644]
While it is positive that the VIP-Reader is not mentioned any longer as an example that the SC can be met, the Understanding says: "Currently, this SC can not be reliably tested in PDF user agents". One might get the impression that the SC can be met and that it is "just" a testability issue. Are there any valid indicators that the SC is _doable_ with PDF-Content at all. In case it is not even doable, which I would say is the case,  and there is no real PDF-Reader (not a converter) I would say it is impossible to meet this SC which would make the SC technology-specific.

**Comment by alastc** [comment]
As per issue #656, if there are objections about feasibility for PDFs or applications, then the main option is to narrow the scope to markup languages. I'm not sure what other option there is?

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment, we have integrated a change to avoid issues with PDF and application scenarios, so the SC text starts:

"In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by setting all of the following and by changing no other style property."

The purpose of the SC is to encourage people to enable over-riding of content via user-agent mechanisms, rather than require on-page widgets. Therefore the working group would like to avoid 'mechanism is available' language for this SC as people tend to read it as meaning adding a widget to a page.
