### ISSUE TITLE
Success Criterion 1.4.13 Content on Hover or Focus

### ISSUE THREAD

**Issue by milk54** [w3c/wcag21#650]
Is the tab menu included in this success criterion?
The accessible tab menu displays the content when it receives the focus.
Of course, Tab menu displays the content by clicking. So Do not include those that work on clicks on this success criterion, is not it?
(Only when hover or focus only？ )

I do not know how to techniques this Success Criterion, so I would like you to provide many concrete examples for easy understanding.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. Tabbed interfaces and similar selections, such as a drop-down box, that may cause additional content to become visible on focus/selection were not intended to be covered by this criterion. Rather, the criterion was designed for content that also becomes hidden when focus (or hover) is removed. We agree the criterion text did not reflect this well and made a change so that it now reads:

> Where receiving and removing pointer hover or keyboard focus triggers additional content to become visible and hidden, respectively, the following are true: ...

This scopes out tabbed interfaces because the removal of focus does not then hide the content because it is still selected. In this case, it might seem like the content is removed when the tab loses focus, but the content is actually changed when a different item receives the focus. We hope this addresses your concerns.

Regarding techniques, the working group will be working hard on the supporting understanding and technique materials in the next few months.

**Comment by milk54** [comment]
I understand. Thank you.
