### ISSUE TITLE
Simplifying 1.4.13 Content on Hover or Focus and making it easier to apply to software and documents

### ISSUE THREAD

**Issue by mapluke** [w3c/wcag21#655]
If the key part of the exception is moved to the start of the SC text the reference to “user agent” can be removed. This makes this SC much easier to understand and much easier to apply to software and documents (which is the task of the team working on the European EN 301 549 standard update).

The first line would then read:
Where the author causes the hover or keyboard focus to trigger additional content to become visible, the following are true:

with the bullets remaining unchanged and the exception being removed.

**Comment by awkawk** [comment]
Perhaps:
Where the author causes the hover or keyboard focus to trigger additional content to become visible and controls the visual presentation, the following are true:

**Comment by awkawk** [comment]
(Official WG response)
Thank you for your comment. The existing exception language was carefully worded with input from many working group members and is used in other draft criteria (Graphics Contrast and Target Size). The language you proposed does not seem to address the key technology-specific exception of the `title` attribute, because the author has full control of its existence. The distinction about the user agent is needed to identify that the author may not be able to control the visual styling or behavior on hover or focus, but they do control its existence.

It may be possible to apply this to documents and software with the same intentions simply by re-interpreting the "user agent" in those cases. For example:

**Software:** If the user agent is the OS, then it gives exception to wherever the OS may generate tooltips or similar applicable content and the developer uses the default presentation or has no ability to change it.
**Documents:** If the authoring software is the user agent, then the exception is again given to hover or focus content that the document author cannot style.
