### ISSUE TITLE
"Accessibility Supported" - SC 2.6.1 Motion Actuation

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag21#676]
The 1st exception reads "Accessibility Supported: The motion is used to operate a keyboard, pointer, or assistive technology;"

The term "Accessibility Supported" is a term defined in WCAG 2.0. It can be read as if this SC does not apply to the motion if the motion is "Accessibility Supported". So it is confusing.

definition of "accessibility supported"
https://www.w3.org/TR/WCAG21/#dfn-accessibility-supported

Is there any other phrase than "Accessibility Supported" to describe the 1st exception? For example, "Indirect Motion" or something.

Plus, the concrete examples of this exception are needed in Understanding document so that readers can understand this exception more easily.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for the comment. We are updating the SC and modifying the first exception so that it starts with the description "Supported Interfaces", but the phrase "accessibility supported" is still used in the description, as follows:

"The motion is used to operate functionality through an <a>accessibility supported</a> interface;"

The Understanding document will be updated to reflect clearly that the intent is that where motion is used to operate an interface that has accessibility support (meaning that it has user agent and assistive technology support) that motion is exempt. For example, a user might use a head mouse system that operates using the camera in order to interface with the pointer/mouse interface would be exempted. We hope this addresses your concern.
