### ISSUE TITLE
General comments on success criteria 1.3.4 and 1.3.5

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag21#684]
ETS does not support the inclusion of success criterion 1.3.4 (in any form) at level A or AA. We maintain that these proposals are inadequately grounded in research regarding what measures can best improve the accessibility of the Web for users with learning and cognitive disabilities. Moreover, insufficient implementations (and implementation experience) have been developed to justify their inclusion at Level A or AA. Indeed, we are concerned that insufficient implementations exist to merit inclusion of 1.3.5 at all, and doubt that it could meet the exit criteria of a Candidate Recommendation (notably the requirement for demonstrable "accessibility support").

Evidence-based measures to enhance the accessibility of the Web to users with learning and cognitive disabilities are highly desirable, important to develop, and suitable for standardization once adequate experimentation has been undertaken to arrive at efficacious, broadly applicable solutions.

**Comment by joshueoconnor** [comment]
[DRAFT RESPONSE] We acknowledge your considered feedback and stance on the SC 1.3.4, however many in the working group feel that this important success criterion is a part of a suite that can create a cohesive personalisation matrix that can be built upon in the future. This work can be continued either within WCAG 2.2 or even in other fora but many in the group support this SC and it's inclusion within WCAG 2.1.

**Comment by awkawk** [comment]
(Official WG Response)
We acknowledge your considered feedback and stance on the SC 1.3.4, however many in the working group feel that this important success criterion is a part of a suite that can create a cohesive personalisation matrix that can be built upon in the future, and with SC 1.3.4 and the now-reduced requirements there are implementations that support this SC. For SC 1.3.5, the SC will be listed as "at risk" in order to establish whether a sufficient level of implementations exist. This work can be continued either within WCAG 2.2 or even in other fora but many in the group support these SC and inclusion within WCAG 2.1.
