### ISSUE TITLE
Internationalization implications of 1.4.12

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag21#685]
Success criterion 1.4.12 requires that "no loss of content or functionality occurs by setting all of the following..." The four style properties listed include letter spacing and word spacing, which seem problematic when applied to non-alphabetic writing systems (e.g., East Asian typography), including application to contexts in which there are no spaces between words.

This success criterion should be reviewed by specialists in internationalization (including East Asian typography). It may be necessary to add an exception clarifying that only the text style properties applicable to the writing system in use need satisfy the requirement (i.e., one should ignore the inapplicable style properties when applying the success criterion to documents or fragments of text to which only some of them are relevant). Adding a note to the Understanding document would not suffice to clarify the issue in the normative text, but a note or exception in the specification itself would be appropriate (if the issue is found to be substantive after consultation with suitably qualified reviewers).

If feasible under the constraints of the W3C Process, it may be possible to review this matter further at the Candidate Recommendation stage, but this is obviously complicated by the very limited opportunities for introducing changes once a specification has reached CR.

**Comment by mraccess77** [comment]
I am not an expert but in certain forms of writing (syllabic) it would seem that inter-word spacing could provide cues to people.
https://www.sciencedirect.com/science/article/pii/S0042698907002556

**Comment by alastc** [comment]
Happy to get a review. From a little testing I *think* that when using CSS is used to do vertical text, the aspects from this SC work, just in a different direction. Whether they provide the same advantage to low vision people is another matter though, I'm not sure.

Prehaps we could ask @MakotoUeki. I did contact Richard Ishida before, and he was very helpful, evenutally. (Very busy man!)

Now, how do I turn off Stylish? Everything is kinda spaced out now... ;-)

**Comment by MakotoUeki** [comment]
Please see https://github.com/w3c/wcag21/issues/677

In Japanese, we don't put white space between words. So "Word spacing" needs to have exception for Japanese at least.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. These properties are defined in CSS and in typographical principals, and they adhere to the meaning used in CSS. We will modify the description for paragraph spacing to "spacing following paragraphs" instead of "spacing underneath paragraphs" to address the implicit western language bias in this item. We will also add the following exception to address cases such as in Japanese where word-spacing is not typically used.

Exception: Human languages and scripts which do not make use of one or more of these text style properties in written text can conform using only the properties that are used.

https://github.com/w3c/wcag21/pull/729
