### ISSUE TITLE
Comment on 2.4.11

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag21#688]
The principal rationale asserted for this success criterion is that one or more speech recognition systems inappropriately forwards dictated text to Web applications when no control that accepts text input has the keyboard focus. This is an accessibility problem that merits a solution for users of speech recognition systems - especially those with disabilities.

The current proposal seeks to solve this problem by requiring every relevant Web application to include options whereby users can turn off or remap the single character key shortcuts used in the application. The cost of this proposal is borne by Web content (especially application) implementers, and by users of affected speech recognition technology, who must find and change an option in every application that uses a single character key shortcut (where the controls responding to the shortcut are not in focus). A personal needs and preferences profile could in theory be used to simplify the configuration process, but, to date, no interoperable Web standard is available to support this approach.

A more effective and better engineered solution would make use of accessibility APIs (e.g., at the operating system level) by speech recognition tools to ensure that spoken input is not processed as dictation unless a user interface control that accepts text input has the keyboard focus. Proponents of this success criterion have repeatedly asserted (without substantive technical arguments and without the involvement of the various speech technology vendors) that the acknowledged problem cannot be solved by speech recognition tools.

Given the difficulties summarized above with the rationale for this proposal, it should be deferred for further consideration in a forum that engages speech technology developers, ARIA and accessibility API developers, to investigate the available options for solving the underlying accessibility problem. That is, this proposal should not proceed to CR.

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. We understand your desire to avoid imposing requirements on authors that might best be addressed by UA or AT, and believe that the current language's use of "a mechanism is available" helps ensure that solutions exist for end users in the near term but also provides a way for improvements in UA and AT support to remove this responsibility from authors. Today, with no AT or UA support, web applications like gmail can readily implement support (and have) for this SC. Since this SC is focused on developers who are implementing custom keyboard shortcuts, it is not expected that this SC will pose a challenge for most sites. We will clarify this in the understanding document to ensure that authors know how to evaluate whether UA and AT support exist and what techniques are available to meet this SC.
