### ISSUE TITLE
The Paciello Group comment on 1.4.10 Reflow

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag21#694]
In the understanding document https://www.w3.org/WAI/WCAG21/Understanding/21/reflow.html 

> For organisations which are using legacy systems or are not able to update their layout methods for some reason, an alternative conforming version could be a mobile site which has a fixed 320px wide layout.

Ideally, this mobile site should be reachable from the non-mobile layout (i.e. user doesn't have to guess what the "m." domain may be, or change their user agent to trigger UA-sniffing). The understanding document should clarify that a mechanism needs to be available for a user to clearly choose to go there (rather than reliance on factors outside of their control - see also the new note added to 5.1.2 Full pages)

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by alastc** [comment]
I'll take that as an action to update the understanding doc

**Comment by awkawk** [comment]
(Official WG Response)
Thank you for your comment. We will mark this issue with the "implementation follow up" label for work in the understanding document.

**Comment by WayneEDick** [comment]
I will take this action.
I have used many mobile pages with varying success.
Here are the factors to consider.

-  Does the mobile page require a mobile emulator to run? Emulators generally don't integrate with other tasks you perform on the web.
- Does the emulator work well on the landscape displays of laptops and desktops?Are there fixed headers and/or that overpower the main content.
- If the developers presents the mobile page are they committed to keep it accessible throughout design changes? One long term problem faced by people with low vision is the unofficial assistive technology. If a development group does not acknowledge the assistive value of a feature they are likely to change it so that it no longer works. 

I would say that a mobile page that does not require an emulator and is fully functional in the landscape mode of computer screens would be fine until the development team makes a significant site modification.

Wayne

**Comment by alastc** [comment]
HI Wayne, 

I'm not sure what you mean by emulator? That sounds like an app environment, rather than a browser?

It would be worth having a look at the understanding doc, I think the comment has been dealt with.

Thanks,

-Alastair

**Comment by WayneEDick** [comment]
​​
Hi Alistair,

Sometimes you can access a mobile page directly, but other times you can
only access it if you place your browser in an emulator mode. An example of
this is the Chrome extension called User Agent Switcher. Using this you can
use the IOS web page for say GMail or GitHub. You cannot get these formats
from say Chrome on Mac OS or Windows. I would not consider this as a
satisfactory solution because such emulation apps tend to put your entire
browser into a mobile mode. Not all tabs can handle this format gracefully.

Wayne.


On Sat, Mar 10, 2018 at 1:38 PM, Alastair Campbell <notifications@github.com

**Comment by alastc** [comment]
Ah, that's what Patrick referred to as "user-agent sniffing", calling it an emulator might throw people.

That wouldn't be a valid way to conform, the understanding doc mentions this, and it's covered by the conformance model.

**Comment by patrickhlauke** [comment]
> That wouldn't be a valid way to conform, the understanding doc mentions this, and it's covered by the conformance model.

I hope you meant "NOT a valid way to conform"? not au-fait with whatever the latest version of the understanding is, but am hoping the idea of having the mobile site reachable from the non-mobile/desktop version (without the need for users to fake their UA etc) makes it in...

**Comment by lauracarlson** [comment]
Hi Patrick and all,

On Sun, Mar 11, 2018, 5:41 AM Patrick H. Lauke wrote:

> am hoping the idea of having the mobile site reachable from the
> non-mobile/desktop version (without the need for users to fake their UA
> etc) makes it in...
>
> Perhaps that could be listed as a future technique in the understanding
doc?

Laura

>

**Comment by WayneEDick** [comment]
I agree with Patrick. I just tried to do my morning reading with a user
agent switcher, it is very difficult. (the Chrome User Agent Switcher).

"Mobile site reachable from a non-mobile browser" is the key phrase. The
fake mobile browsers are just too flakey.

Is there a technique to look at yet?

Wayne

**Comment by lauracarlson** [comment]
Hi Wayne and all,

 @WayneEDick wrote:
> Is there a technique to look at yet?

I haven't seen one. If you, @patrickhlauke, or anyone else wants to write one, I am sure it would be welcomed.

-  [Editing Techniques](https://github.com/w3c/wcag21#editing-techniques)
- [Technique Template](https://github.com/w3c/wcag21/blob/master/techniques/technique-template.html)

Thanks,
Laura

**Comment by alastc** [comment]
Hi @patrickhlauke I did mean "Would not" (which is what "wouldn't" means!?!)

This is the [update made](https://github.com/w3c/wcag21/issues/694), I'm sure @allanj-uaag would be happy to update with improvements if you can suggest them.

In terms of techniques, what we're talking about is an alternative conforming version, and we have several for that already including:

- [G136](https://www.w3.org/TR/WCAG20-TECHS/G136.html): Providing a link at the beginning of a nonconforming Web page that points to a conforming alternate version
- [C29](https://www.w3.org/TR/WCAG20-TECHS/C29.html): Using a style switcher to provide a conforming alternate version

I think either of those would be reasonable?

**Comment by patrickhlauke** [comment]
> Hi @patrickhlauke I did mean "Would not" (which is what "wouldn't" means!?!)

strangely, i misread that as "would" when i saw the email notification fly in. my mistake. as you were.

**Comment by WayneEDick** [comment]
Alistair,
You did it again.
Yes those two should do it.
if we had a good example that would really do the job.

Wayne

On Mon, Mar 12, 2018 at 6:13 AM, Alastair Campbell <notifications@github.com
