### ISSUE TITLE
Intopia Feedback – SC 1.4.11 Graphics Contrast

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#709]
1.	State; examples should include ‘error’.
2.	SC requires 3:1 against adjacent color(s) – this still allows for dark blue non-underlined links mixed with black text as the contrast would be measured again the page background, eg white. This will still pose a problem for older people with reduced contrast acuity and some people with low vision.
3.	Infographics should be specifically called out in the Understanding doc
4.	The ‘exceptions’ (logotypes, sensory & essential) have been listed in Understanding – we recommend moving these back to the TR like they are for other SC

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by alastc** [comment]
Hi Andrew (Arch),

I've been working on understanding doc updates, on a couple of your points:

1) State, adding 'error'. That isn't a usual state of an input (e.g. for user agents), although I appreciate it is a common state when filling forms in. @johnfoliot I remember you adding the states definition, is there any harm in adding error as a state?

2) I beleive this is already caught by 1.4.1 use of color, here's the technique [G183](https://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/G183).

3) Infographics are simply large, multi-part graphics for this SC, I couldn't think of much to call out apart from this:
> Infographics can mean any graphic conveying data, such as a chart or diagram. On the web it is often used to indicate a large graphics with lots of statements, pictures and charts or other ways of conveying data. In the context of graphics contrast, each item within such an infographic should be treated as a set of graphical objects, ragardless of whenter it is in one file or separate files.

Is that what you had in mind, or was there another aspect.?

4) Exceptions: there has been a delay in updating the understanding since the updates to the SC at TPAC, calling out those exceptions explicitely in the understanding is a mistake. At TPAC it was decided that each of the exceptions basically comes down to 'essential', so I will be updating that section to aling with the SC text.

**Comment by awkawk** [comment]
(Official WG response)
Thank you for the comment. We are marking this with the "implementation follow up" label for work in the understanding documents.

**Comment by awkawk** [comment]
Also adding that your second example refers to text. This SC covers non-text content. Use of poor contrast color to distinguish link text is already addressed in WCAG 1.4.1. See https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F73
