### ISSUE TITLE
Intopia Feedback – SC 2.5.3 Target Size

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wcag21#717]
1.	A layman’s definition is needed for CSS pixel, else this SC will not be adopted
2.	We have concerns about the about the ‘inline’ loophole
a.	We would have liked to have seen SC 2.5.4’s inline requirement included

**Comment by awkawk** [comment]
Thanks you for your comment. The deadline for comments has passed, but the Working Group will make efforts to consider your comment and any suggestions for improvements.

**Comment by awkawk** [comment]
Thank you for your comment. We address the two issues you are raising in turn.

1. Layman's definition of CSS Pixel:

A definition of 'CSS pixel' exists in the WCAG 2.1 draft: https://www.w3.org/TR/WCAG21/#dfn-css-pixels

(Official WG Response)
The concept of CSS pixel is unfortunately not easily explained in lay terms. We believe that for people implementing or testing the SC, the definition needs to be technically precise.

Due to the wide range of physical screen resolutions and device-reported (virtual) resolutions, measuring target size is only reliably possible by reference to CSS pixel dimensions. There is free software available to measure target sizes on screen, for example, "A ruler for Windows" http://www.arulerforwindows.com/index.html https://www.w3.org/TR/WCAG21/#dfn-css-pixels

To address your concern, we suggest to add the following introductionary sentence:

"CSS pixel is a concept that separates the visible area, or pitch, of a CSS pixel from the actual physical screen pixels used to represent it. This allows for an objective test across devices rather than tests which are completely dependent on the end user device, of which the author has no knowledge or control."

2. Inline target loophole

Several public and member comments to drafts of WCAG 2.1 have indicated that the application of the target size requirement to inline text targets would have a significant impact on screen layout, especially as adjacent lines would need a wide line spacing or a large text size if they are to meet the requirement. This can negatively impact usability as it would reduce the amount of text visible at the same time. The WG therefore decided to exempt targets in inline text .
