### ISSUE TITLE
SC 2.5.3 Target Size shouldn't specify a specific size; should be in Techniques instead

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag21#754]
With the massive shift to the use of touch-screen devices for interacting with web content, it makes sense to address touch target issues.  However, the specific reference to a specific target size belongs in Techniques.  This shift will also aid in a future WCAG2ICT-ization of this SC.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by mbgower** [comment]
[Draft response]
Thank you for your comment.
In order to make the SC testable and verifiable, there needs to be a metric to validate, and size has been adopted. Significant discussion was focused on what was achievable, measurable and beneficial for a target size in various contexts and situations. If you have suggestions for how this SC could be made testable without specifying size, we would welcome that information.

**Comment by DavidMacDonald** [comment]
I've created a preliminary discussion draft of WCAG2ICT for the new SCs.
http://davidmacd.com/WCAG/wcag2ict-21-discussion.html

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
