### ISSUE TITLE
Appreciate scoping of SC 1.4.12; original scoping would also be OK

### ISSUE THREAD

**Issue by peterkorn** [w3c/wcag21#759]
In the 7Dec17 draft of SC 1.4.12, the language is scoped with the opening phrase "If the technologies being used allow the user agent to set text style properties".  The new scoping drops "user agent", focusing instead on "content implemented using markup languages".  This is OK, but the prior scoping has a key positive property this lacks: It interacts well with WCAG2ICT's definition of "user agent", and so would apply to things like e-Book readers, on-line help systems (applications that "retrieve and present documents") - even where the content is plain text, but would NOT apply to general parts of a software user interface

The Exception is a good improvement over the 7Dec17 draft.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by lauracarlson** [comment]
[Unofficial proposed response]

Thank you for bringing this to our attention. It is good to know how the WCAG2ICT's User Agent definition worked well with the scoping of this SC in our December draft.

It would be great if the scope could be reverted. Unfortunately, the change is needed because the SC is not achievable in PDF and cannot be reliably tested in PDF user agents.

Consequently, we are pleased that you consider the current wording OK. If the situation changes, the Working Group would be happy to revisit in future guidelines.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 1 week. If we haven't heard a response in a week we will regard the resolution as satisfactory.
