### ISSUE TITLE
Editorial. Some of the glossary definitions have periods at the end and some do not. 

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#778]
Some of the glossary definitions have periods at the end and some do not.  Let's make a decision and go with that. I suggest adding a period but am more concerned about consistency.

**Comment by awkawk** [comment]
There are very few that have periods. Most are not sentences, so we don't capitalize the first word and don't use end-sentence punctuation. Text alternative is an exception (https://www.w3.org/TR/WCAG21/#dfn-text-alternative).

Also of interest is the def for Target, which starts with a phrase but then also has a sentence, which makes me think that the sentence should be a note as it can be viewed as a clarification on the definition text. (all of the notes are treated as sentences/paragraphs)

**Comment by Ryladog** [comment]
First Basic Response:
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:

[Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
[Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
https://www.w3.org/WAI/WCAG21/comments/#issuenotification - How to limit notifications from GitHub

**Comment by Ryladog** [comment]
Proposed WG Response:

Thank you for the comment.  

The Working Group has decided on this paradigm for definition formatting;   

- not to capitalize the first word of definition (unless it is a full sentence)
- not to use end-sentence punctuation (unless it is a full sentence)

Additionally, the term Target will be changed. The second paragraph will become a Note. it will then be;
Note
If two or more touch targets are overlapping, the overlapping area should not be included in the measurement of the target size, except when the overlapping targets perform the same action or open the same page.

**Comment by Ryladog** [comment]
Proposed WG Response:

Thank you for the comment.

The Working Group has decided on this paradigm for definition formatting;

- not to capitalize the first word of definition (unless it is a full sentence)
- not to use end-sentence punctuation (unless it is a full sentence)

Because definitions are intended and are to supposed to be able to replace the term in the Success Criteria text.

Additionally, the term Target will be changed. The second paragraph will become a Note. it will then be;

Note
If two or more touch targets are overlapping, the overlapping area should not be included in the measurement of the target size, except when the overlapping targets perform the same action or open the same page.

**Comment by awkawk** [comment]
Changes implemented to the target definition (https://github.com/w3c/wcag21/commit/2d74ae0f7b033acd8f71afed99ea4d3dd87656ac)

Verified that all WCAG 2.1 definitions are handling sentence case correctly.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
