### ISSUE TITLE
Understanding Label   in Name

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#788]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#label-in-name"   target="_blank">2.4.12 Label in Name (A) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/label-in-name/understanding/21/label-in-name.html"   target="_blank">Understanding Label in   Name</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the content.</p>

**Comment by devarshipant** [comment]
Hi,

Some observations:

1. There are instances where a **label** is (or provides) an **accessible name**, E.g. 
```
<label for="something">First Name</label>
<input type="text" id="something">
```
Here, First Name is a visible label and also the name. I think the Understanding section needs to mention that visible text label is the accessible name in many cases. And there are instances where visible text 'Matches' the accessible name.

2. The Failure (Accessible Name does not contain the visible label text) may not be one when text controls do not have a visible label. For example, a placeholder attribute (or an equivalent attribute like title) and aria-label could satisfy visible and programmatic aspects. E.g., Search textbox, Username, Password, Combobox Filters, Controls in Data tables.

**Comment by mbgower** [comment]
> The Failure (Accessible Name does not contain the visible label text) may not be one when text controls do not have a visible label. For example, a placeholder attribute (or an equivalent attribute like title)

I wanted to clarify that placeholder text is not considered a replacement for a label in the [HTML5.2 specification](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute)

> The placeholder attribute should not be used as an alternative to a label.

or in [aria](https://www.w3.org/TR/wai-aria-1.1/#aria-placeholder):

> Authors SHOULD NOT use aria-placeholder instead of a label as their purposes are different: The label indicates what kind of information is expected. The placeholder text is a hint about the expected value. See related aria-labelledby and aria-label.

Use of the TITLE attribute for a label is allowed (but discouraged) in WCAG, and its value is taken into account in the accessible name specification. It does not stand as an example of a non-visible label, since it is visible (and so could be found and announced by someone using speech recognition) , just not persistent. 

> and aria-label could satisfy visible and programmatic aspects ( E.g., Search textbox...

 If a "search" button appeared after an input with no label, then I agree that aria-label="search" is a possible solution; however, the chances for the engine getting confused between whether the user wants to activate the search button or reposition to the search input field is problematic.

So my take would be that issues with missing labels (or sub-par workarounds) will likely fail existing WCAG 2.0 requirements or lead to confusion.

**Comment by mraccess77** [comment]
In my opinion a title attribute could not be used as the sole source of a visible label under SC 3.3.2 because most user agent implementations don't expose it on keyboard focus.  I would imagine that finding a title attribute for speech input user would be difficult and it would not be visible on mobile.  Title attributes could be used to meet SC 1.3.1 or 4.1.2 if the provide they same meaning as what is covered with presentation.

**Comment by mbgower** [comment]
@mraccess77 yes, especially given that many speech users have mobility issues (i.e., are using the speech control to compensate for an inability to use a pointer and/or keyboard), title with only user agent behaviour seems like a sub-par solution. I just wanted to flag that I think TITLE _is_ part of the accessible name formula, and so enters into the discussion for meeting this SC.

**Comment by awkawk** [comment]
>  It is unorthodox, but does the following fail WCAG 2.1?
> `<input type = "text" placeholder = "enter social, xxx-xx-xxxx">`

If someone found that the placeholder text was exposed by the accessibility API even after text was entered into the control it _might_ be regarded as passing 4.1.2, but as soon as someone filled it in there would be no label available so unless there was a redundant text label it would fail 2.4.6 in WCAG 2.0. This is not encouraged, obviously.

**Comment by mraccess77** [comment]
In my opinion placeholder text is fallback content just like the src attribute might be on an image without alt and therefore fallback content should not be considered as part of the accessible name.  I would fail this for both visual labels and programmatic labels because the visual label goes away when the field has data.

**Comment by mbgower** [comment]
> Correct me if I am mistaken here--the value of placeholder attribute becomes the accessible name if no other primary accessibility attribute exists

There are no occurrences of <code>placeholder</code> in the [Accessible Name and Description Computation](https://w3c.github.io/accname/)'s latest editors' draft; there are many references to <code>title</code>. So on top of both the [warnings about its usage cited earlier](https://github.com/w3c/wcag21/issues/788#issuecomment-380603071), and observations about its disappearance visually, I don't think it is correct to say it would be considered part of the accessible name. @michael-n-cooper, perhaps an explicit note about it might be warranted?

**Comment by devarshipant** [comment]
> There are no occurrences of placeholder in the Accessible Name and Description Computation's latest editors' draft; there are many references to title. So on top of both the warnings about its usage cited earlier, and observations about its visual disappearance -- either of which I think is reason to not consider it as an acceptable solution for this SC -- I don't think it is technically correct to say it would be considered part of the accessible name?

Agreed. Sorry, but I am only questioning -- why does title attribute get preferential treatment over placeholder? Title attribute disappears too. And it's implementation is widely misunderstood w.r.t how screen readers process it. 

This is how I arrived at this conclusion where placeholder gets calculated as the acc name. It checks out with JAWS and NVDA, but I don't know if vendors are reading the Acc Name algorithm to calculate placeholder. Or reading it at all.

[HTML 5 says ](http://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute)"**User agents should present this hint to the user**, after having stripped line breaks from it, when the **element's value is the empty string** and the control is not focused (e.g. by displaying it inside a blank unfocused control)."

Hint = "value of placeholder"

Tie that in with the following [Acc Name Cal](https://w3c.github.io/accname/#mapping_additional_nd_te):

G. Otherwise, if the current node is a Text node, return its textual contents. [1]

Text Node = "value of placeholder on the **input element**"

To my mind the hint that user agents give (which is the value of the placeholder) is the innertext being computed in G.

1. Text Node: Type of DOM node that represents the textual content of an attribute or an **element**. A Text node has no child nodes.

**Comment by mbgower** [comment]
> why does title attribute get preferential treatment over placeholder? Title attribute disappears too.

Title is not considered a great implementation; I can't find it right now but there's a note somewhere cautioning against its use. That said, the way user agents display the value of the title attribute is not visibly persistent but it is visibly consistent: hovering your mouse over the item and it will always redisplay the value. In the case of placeholder, once the input field has any value populated, the ability to view the value of placeholder is lost.

**Comment by jake-abma** [comment]
@mbgower got some for you:

https://www.w3.org/WAI/tutorials/forms/labels/#using-the-title-attribute

https://html.spec.whatwg.org/#the-title-attribute

http://www.html5accessibility.com/tests/title-usage.html

http://w3c.github.io/html/dom.html#the-title-attribute

https://developer.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/

**Comment by mbgower** [comment]
Thanks @jake-abma

**Comment by devarshipant** [comment]
> That said, the way user agents display the value of the title attribute is not visibly persistent but it is visibly consistent: hovering your mouse over the item will always redisplay the value. 

Great points. However, the number of controls and meaningful context around the controls makes a difference when recommending title or placeholder. 

Here is a mock up showing Log in page using placeholder text. 

1. Would it pass if only title attributes were used?

2.  Would it pass using placeholder (sufficient context is provided)?

<img width="445" alt="placeholder" src="https://user-images.githubusercontent.com/7377040/38872816-b1f9cc4a-4243-11e8-8504-565ddf66534e.PNG">

> In the case of placeholder, once the input field has any value populated, the ability to view the value of placeholder is lost.

It can be viewed on pressing the escape key. But you are correct, it is not as helpful as title.

**Comment by lseeman** [comment]
Can we add that 
1. having the visible labels provides support for people with learning and cognitive disabilities? 
2. using the most common terms in the label helps people with a limited vocabulary understand the label,

**Comment by Itakora** [comment]
Can you please tell me if this would be a good or bad practice for this criterium?
&lt;button aria-label=”Close”&gt; X &lt;/button&gt;

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#352
