### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by allanj-uaag** [w3c/wcag21#79]
<h2>SC Shortname</h2>
Font Family
<h2>SC Text</h2>
The user can change the font family to any available to the user agent.
<h2>Suggested Priority Level</h2>
Level AA
<h2>Related Glossary additions or changes</h2>
none
<h2>What Principle and Guideline the SC falls within.</h2>
Principle 1, <a href="https://www.w3.org/TR/WCAG20/#visual-audio-contrast-scale"> Guideline 1.4.4</a>
<h2>Description</h2>
Simply Put: You can choose the font you need for reading and finding buttons.
<h2>Benefits</h2>
<blockquote>
  <p>Some fonts/typefaces are more readable than others. For example, some people cannot read fonts with sub-pixel rendering. </p>
  <p>When users are changing fonts, it is best if they can see the fonts before making a selection, so that they do not select a font that is unreadable to them. For example, the fonts in a list are presented in their font ("Times" is in Times, "Verdana" is in Verdana, etc.), as in the figure below.</p>
  <p><strong>User Need</strong>:  Users can change the font face (also called font family or typeface) of all text, choosing from a wide range of fonts including sans serif and serif fonts.. <br>
    Source: <a href="http://w3c.github.io/low-vision-a11y-tf/requirements.html#font"> Accessibility Requirements for People with Low Vision, Section 3.3.2</a></p>
</blockquote>
<h2>Testability</h2>
<ol>
  <li> Confirm that font family names appear in that font </li>
  <li> Select font family name which appears readable </li>
</ol>
<h2>Techniques</h2>
<h3>Existing Relevant Techniques</h3>
<ul>
  <li> <a href="https://www.w3.org/TR/WCAG20-TECHS/G117.html"> G117: Using text to convey information that is conveyed by variations in presentation of text</a> </li>
  <li> <a href="https://www.w3.org/TR/WCAG20-TECHS/G153.html"> G153: Making the text easier to read</a> </li>
</ul>
<h3>New Techniques</h3>
$$New technique: Title$$
<h2>Related Information</h2>
<h3>Actions</h3>
<ul>
  <li> <a href="https://www.w3.org/WAI/GL/low-vision-a11y-tf/track/actions/70"> Action-70 Write Font SC</a> - on Wayne Dick, August 25, 2016 </li>
</ul>
<h3>Email</h3>
<ul>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0053.html"> Re: Tracking Success Criteria Progress</a> - Erich Manser, 14 September 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Sep/0014.html"> Re: lvtf-ACTION-70: Write font sc</a> Wayne Dick, 5 September 2016</li>
  <li> <a href="https://lists.w3.org/Archives/Public/public-low-vision-a11y-tf/2016Feb/0042.html"> Requirements doc</a> - Alastair Campbell, 18 February 2016 </li>
</ul>
<h3>GitHub</h3>
None
<h3>Minutes</h3>
<ul>
  <li><a href="https://www.w3.org/2016/05/19-lvtf-minutes.html#resolution02"> 1 December 2016 LVTF teleconference</a> <a href="https://www.w3.org/2016/12/01-lvtf-minutes.html#item06"> 19 May 2016 LVTF teleconference</a> </li>
</ul>
<h3>Resolution</h3>
<ul>
  <li><a href="https://www.w3.org/2016/12/01-lvtf-minutes.html#resolution06"> Ready for WCAG</a> - 1 December 2016 </li>
</ul>
<h3>Wiki Pages</h3>
<a href="<a href="">Tracking Success Criteria Progress</a></a>

**Comment by DavidMacDonald** [comment]
seems like a User Agent Issue

**Comment by liamquin** [comment]
On Thu, 2016-12-01 at 13:47 -0800, allanj-uaag wrote:
> 
> [...]

>  For example, the fonts in a list are presented in their font
> ("Times" is in Times, "Verdana" is in Verdana, etc.), as in the
> figure below.</p>

This is unacceptable for non-Western fonts. For example, most Microsoft
non-Latin language packs provide fonts with Ariel (or similar) glyphs
for the Latin alphabet, and the font names are mostly in the Latin
alphabet. Or, the font might not actually contain the glyphs to
represent its own name, or, in the case of a digbat font, the
characters might appear as non-text symbols or emoji.

Instead, for OpenType fonts the sample text provided for this purpose
in the font should be used where available, or allow the user to type
characters in a sample preview box, using their preferred input method.

> 
>   <li> Confirm that font family names appear in that font </li>
>   <li> Select font family name which appears readable </li>

suggest,
    <li>Confirm that font samples appear in the appropriate fonts</li>
    <li>Select font which appears readable</li>
    <li>Confirm that the choice is then used to render text.</li>
Best,

Liam

-- 
Liam R. E. Quin <liam@w3.org>
The World Wide Web Consortium (W3C)

**Comment by DavidMacDonald** [comment]
Seems to be a duplicate with #79

**Comment by liamquin** [comment]
On Fri, 2016-12-02 at 00:25 -0800, David MacDonald wrote:
> Seems to be a duplicate with #79
That's because this _is_ 79 :-)

>

**Comment by emanser** [comment]
I would like to volunteer as SC manager for 79. Thank you

**Comment by mbgower** [comment]
> The user can change the font family to any available to the user agent. 

How is the author supposed to control the user agent? This seems like another of the candidate SC which would be met automatically with most browsers, and which otherwise is tough to author.  http://www.howtogeek.com/208552/how-to-change-the-default-fonts-in-your-web-browser/
I question the value of a SC which is just going to be rubber stamped as passing.
I'm trying to think of how this could be modified to cover CSS. A technique already exists that could meet it. that is already covered under 
[C22: Using CSS to control visual presentation of text](https://www.w3.org/TR/2010/NOTE-WCAG20-TECHS-20101014/C22)
Overall, my suspicion is that this important principle should be part of [UAAG](https://www.w3.org/WAI/intro/uaag), not WCAG.

**Comment by goetsu** [comment]
Is it an invitation for authors to implement feature to let user choose font he want ? in that case better to be AAA I think because can be costly to implement

**Comment by joshueoconnor** [comment]
This is assigned to Erich Manser (awaiting Github ID) - https://www.w3.org/WAI/GL/wiki/SC_Managers_Phase1#Current_SC_Managers

**Comment by mbgower** [comment]
Okay, now that I've reviewed all the LVTF candidate SCs, I'm seeing a number of patterns/repetitions that I'd like to identify and suggest modifications for.
Font Family, Spacing and Text Color all cover visual text attributes. They are all arguably candidate SCs for which there are no authoring requirements. 
To what extent can authors enable or impede the user manipulation of visual text attributes? If we can define things an author should or should not do, I would argue that would form the basis of a single, larger SC.
Looking through the existing SC, 1.4.8 Visual Presentation seems to tackle this fairly thoroughly:

- color can be selected by user
- width is no more than 80 characters
- text is not justified
- line and paragraph spacing
- resize text without horizontal scrolling (more on this one later)
Since these three candidate SCs are all covered under an existing SC, and that SC is at the (unadopted) AAA level, why not modify the AAA criteria to satisfy the goals of these new candidates SCs, and promote 1.4.8 to a AA level?

What I would like to see go into an updated version of 1.4.8 is more details on possible failures which impair a user agent's ability to give users control of Visual Presentation.

Finally, I would suggest that the bullet on resizing text (without horizontal scrolling) could be pulled from 1.4.8, since there are more authoring considerations. I'm inclined to also pull the width info since it is related. I will put my comments regarding width/resize/scrolling into Issue 57, Line Length.

**Comment by lseeman** [comment]
Hi

Please look at use a clear text-and-voice  wcag issue 27  and   visual-presentation wcag issue 51

There is a clear ovelap, however as we say " Provide clear typography (text and numbers),...
we alow for the SC to be met via  personalization

Also we are working on new personalization framework wich might work better then user style sheets

**Comment by allanj-uaag** [comment]
merged with #78

**Comment by lseeman** [comment]
We should merge with https://github.com/w3c/wcag21/issues/27 #27

**Comment by lseeman** [comment]
can we add they can change the voice as well?

**Comment by lauracarlson** [comment]
Hi Lisa,

This issue is closed. See @allanj-uaag  [February 1 comment](https://github.com/w3c/wcag21/issues/79#issuecomment-276726937).
