### ISSUE TITLE
Understanding Status   Changes

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag21#795]
<p>The <a   href="https://www.w3.org/TR/WCAG21/#status-changes"   target="_blank">3.2.6 Status Changes (AA) SC</a> has draft   Understanding content that can be viewed at <a   href="https://rawgit.com/w3c/wcag21/status-messages/understanding/21/status-messages.html"   target="_blank">Understanding Status   Changes</a>.</p><p>Please review the Understanding document   and submit a comment on this issue for any changes that are needed to the   content.</p>

**Comment by guyhickling** [comment]
Will changes made now to these Understanding documents show immediately in these URLs you have given, or will we have to wait until the next official release?

**Comment by alastc** [comment]
Hi @guyhickling, they will update whenever something is merged into the specific 'understanding' branch, which will generally be well before the next official release.

Most of the work Feb/March has been on testing implementations, the understanding docs & techniques will get the focus Apr - May.

HTH,

-Alastair

**Comment by bruce-usab** [comment]
On the call today I volunteered to provide and editorial review.  I have attached an MS Word version showing track changes with my suggested edits.  That is convenient way to work for me, but does it help whoever has lead on this?  I will need some hand-holding to do a pull request instead.  Also I noted some questions.

- The current version has the @@@ which will need a good bit of work.
- The current version kind of intermixes use of page, screen, and viewport.  I think the choices need a little bit more review.

[understanding-sc-326-status-changes.docx](https://github.com/w3c/wcag21/files/1921101/understanding-sc-326-status-changes.docx)

**Comment by mbgower** [comment]
I will incorporate the changes from @bruce-usab . I also want to do a quick pass through of the Understanding document, because the rewording to Status Messages (from Status Changes) slightly reduced the scope of the SC, and some of the more 'best practice' material may now not be appropriate.

**Comment by mbgower** [comment]
Okay, I've incorporated Bruce's changes. https://github.com/w3c/wcag21/commit/b132964a7c292a164f8710395319a9908508532a
@bruce-usab , I slightly modified the first sentence because I found your new one was a bit hard to parse (a lot of possible verbs acting as nouns, etc). I marked most of your stuff resovled. i responded to a few things we might want to think about a bit more.
[understanding-sc-326-status-changes-mg.docx](https://github.com/w3c/wcag21/files/1930663/understanding-sc-326-status-changes-mg.docx)

I have to say, not so humbly, that all the work I did on this seems to have been worth it. I'm pretty happy with how it is looking :) Now @DavidMacDonald and @steverep can rip it to shreds :)

**Comment by DavidMacDonald** [comment]
I've reviewed the document, made a few editorial changes while not changing the substance. The current Branch"Status-Changes" was in conflict with the Master, so after completing edits I created a new branch "status-messages" and copied the status-message file over there. I've made a pull request #872

**Comment by lseeman** [comment]
getting a 404

**Comment by alastc** [comment]
Fixed, I updated to link to David's new branch: https://rawgit.com/w3c/wcag21/status-messages/understanding/21/status-messages.html

**Comment by michael-n-cooper** [comment]
This issue was moved to w3c/wcag#359
