### ISSUE TITLE
2.2.7 Animation from Interactions should be AA not AAA

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#833]
The requirement to allow users to disable animations from user action seems applicable to all content types. It should be AA.

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by mbgower** [comment]
Proposed response:
Thank you for your comment.

A previous draft of this SC used the wording "significant animation" and defined that as:

> Significant animation: animation which continues for more than 3 seconds, affects more than 1/3 of the viewport and may or may not be synchronized with a user action (e.g. parallax scrolling effects)

However, the Working Group [received comments](https://github.com/w3c/wcag21/issues/258) expressing concerns about scope and criteria in the original wording. Because we did not have research to back up these specific requirements, and had concerns that without qualifying language, many potentially helpful animations could cause failures at a AA level, we elected to remove the qualifying wording and introduce this at the AAA level.

Our hope is to gather more research on the nature and scope of animations which can trigger physical reactions for users with vestibular disorders and create a more contained SC which can reside at the AA level in the next version of WCAG.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
