### ISSUE TITLE
5.2.2 Full Pages

### ISSUE THREAD

**Issue by cyns** [w3c/wcag21#844]
I'm not sure that requiring every variation of a page to conform is appropriate. In some cases, variations are used to provide a conforming alternate version. Requiring both to conform essentially removes the option for a conforming alternate.

**Comment by patrickhlauke** [comment]
only if it's possible for a user to switch between the variations. if the variations are triggered by something outside of the user's control (e.g. the size of their viewport, what browser they're using, etc) then it's no good saying "well, if you just open this page in another browser/device/get yourself a bigger monitor/zoom out/etc you can get to the accessible version".

**Comment by awkawk** [comment]
Thank you for commenting. For more information about how the AG WG will process this issue, see the following:
- [Issue Processing](https://www.w3.org/WAI/WCAG21/comments/#issueprocessing) - How the WG will discuss the issue
- [Issue Resolution](https://www.w3.org/WAI/WCAG21/comments/#issueresolution) - Identifying and responding to the official WG response
- [Issue Notification](https://www.w3.org/WAI/WCAG21/comments/#issuenotification) - How to limit notifications from GitHub

**Comment by mbgower** [comment]
[Draft official response]
Thank you for your comment.
There are several Notes that qualify the wording of 5.2.2 Full pages. The first is an existing note from 2.0 that covers _alternatives_ to the page which are used to provide equivalent facilitation (e.g., a long description or an alternative presentation of a video).

The new note is specific to _variations_ generated for various screen sizes. For this second note, the "variations" are a distinct consideration from the "alternatives" addresssed in the first note, and there is parenthetical text making this clear (bolded here for emphasis):

> Each of these variations needs to conform (or needs to have a conforming **alternate** version) in order for the entire page to conform.

So according to the wording, the page variations for screen size must each comply, and where one does not, it must provide its own alternative in order to conform. This needs to be the case so that a user consuming the page in a certain format can receive the entire page accessibly.

Please let us know if this clarifies your concern.

**Comment by awkawk** [comment]
The WG decided on the above response, so we changed the text in the comment containing the proposed response to read "[Official WG Response]". Please confirm is you are satisfied with the response within 3 days. If we haven't heard a response by then we will regard the resolution as satisfactory.
