### ISSUE TITLE
Do we need to update implementation page SC numbers?

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag21#896]
https://www.w3.org/WAI/WCAG21/implementation-report/

https://twitter.com/stommepoes/status/991297421094391808

**Comment by alastc** [comment]
@michael-n-cooper is it worth updating the implementations report to align with the new SC numbering?

**Comment by awkawk** [comment]
I think so.

**Comment by michael-n-cooper** [comment]
First, pointing to a tweet and not providing any other detail is not a good way to file an issue. It took me more time than it should to understand the request here.

Second, the implementation report uses the number for the CR, for which testing was conducted. Changing numbers after the fact could invalidate results or introduce confusion.

Third, it's not straightforward to update this. Probably because of the above. 

So I'm closing wontfix. I did update the WCAG link on the implementation report to the CR, so people will see the same SC numbers and names there as in the report.
