### ISSUE TITLE
Technique Proposal - Question

### ISSUE THREAD

**Issue by kerstinp** [w3c/wcag21#951]
Hi all,

some time ago I delivered a proposal for a PDF technique for WCAG 2.0 (which of course could be also a technique for WCAG 2.1): [https://github.com/w3c/wcag/issues/296](https://github.com/w3c/wcag/issues/296). 

What shall I do with the proposal? I could post it here again or there might possibilites for the admins to copy the issue?

(Because this issue is just a short question it can directly be closed after answering) 

Cheers

Kerstin

**Comment by awkawk** [comment]
@kerstinp We are moving back to the /wcag repository since it makes sense to have one repo for the different WCAG versions so that there is one place to log issues. I labeled that issue with the Techniques label so we will have it in mind.

One big issue with techniques is having a resource to start work on a technique. We will make the template available so anyone interested in offering specific language can do so.
